### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by xyh2132** [WongSaang/chatgpt-ui#10]
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
登录admin后台设置KEY时,提示如上,无法使用

**Comment by WongSaang** [comment]
Did you deploy using the example Docker Compose configuration and access it on local port 9000?

**Comment by xyh2132** [comment]
如果没有，请将环境变量 APP_DOMAIN=host:port 添加到WSGI-SERVER服务--这个如何添加,是写在docker-compose.yaml里吗,写在什么地方可以

**Comment by WongSaang** [comment]
对的，写在 docker-compose.yaml
有截图的话给一张

**Comment by ErmuErmu** [comment]
老哥，我这也遇到同样的问题。
![image](https://user-images.githubusercontent.com/29274217/222676011-5dd21924-77fe-43cb-8c25-d0d9db8391ac.png)

编排文件是这样的
![image](https://user-images.githubusercontent.com/29274217/222675868-6fd3a4af-b4ec-4ce4-96b1-105708608ea7.png)

**Comment by ErmuErmu** [comment]
wsgi-server  添加了 APP_DOMAIN=host:port 环境变量后，问题解决。
