### ISSUE TITLE
The feedback text overlaped in markdown

### ISSUE THREAD

**Issue by ikiwihome** [WongSaang/chatgpt-ui#102]
当你要求GPT用markdown 章节次序回复时，回复内容的一级标题和二级标题重叠
When you ask GPT to reply in markdown chapter order, the first-level and second-level headings of the reply overlap

![image](https://user-images.githubusercontent.com/7870610/228636079-60306529-a9f8-41a4-84bc-633423ff8093.png)

**Comment by WongSaang** [comment]
Hello, thanks for the feedback!
This issue has been fixed in the latest version.
