### ISSUE TITLE
建议增加打字机功能

### ISSUE THREAD

**Issue by ikiwihome** [WongSaang/chatgpt-ui#104]
当前版本内容是直接一段一段出现，需要等待时间较长，建议增加打字机效果

**Comment by GOvEy1nw** [comment]
Typewriter is built in, just not enabled. You can tweak these settings in nuxt.config.ts and build your own version to get it working.

```
            typewriter: false,
            typewriterDelay: 50,
```

**Comment by WongSaang** [comment]
最新的版本可以通过环境变量来配置了
![image](https://user-images.githubusercontent.com/46235412/230265504-f21b1c48-5e47-4501-b8d7-19f976ca84b5.png)
