### ISSUE TITLE
Request: Option to disable creation of new accounts

### ISSUE THREAD

**Issue by bland328** [WongSaang/chatgpt-ui#105]
An environment variable which hides the `Create Account` button and also completely disables account creation functionality would be appreciated.

My goal is to be able to expose my self-hosted instance of `chatgpt-ui` to the open internet, but not allow strangers to attempt to create accounts.

Thanks for considering!

**Comment by spencerwongfeilong** [comment]
u can disable sign up by putting the following in ur administration dashboard

![image](https://user-images.githubusercontent.com/127573355/228869977-d8a3ee6c-a734-4779-82a9-3ded8ae08cc2.png)

**Comment by bland328** [comment]
Thanks very much! I'm unfamiliar with Django, and didn't realize it was so simple.

For anyone else finding this, the setting is under `Chat` > `Settings` > `open_registration`.
