### ISSUE TITLE
Using davinci-003-model instead of chatgpt model

### ISSUE THREAD

**Issue by dannydrinkswater** [WongSaang/chatgpt-ui#11]
First of all, great works!
However, I noticed that it is using the official davinci-003-model rather than the ChatGPT model.
I guess it's better to state that davinci-003-model is used at this state.

**Comment by hyyz17200** [comment]
Yeah I agree. And I would like to see if it can be changed to the new released ChatGPT model.

**Comment by WongSaang** [comment]
Thanks for the feedback, the latest version is already using OpenAI's latest open GPT-3.5 model `gpt-3.5-turbo`, welcome to update it. 😊
