### ISSUE TITLE
DB_URL=sqlite:///home/chatgpt-ui-client/openai.db报500错误

### ISSUE THREAD

**Issue by 1371030** [WongSaang/chatgpt-ui#114]
DB_URL=sqlite:///home/chatgpt-ui-client/openai.db

volumes:
      - "/home/chatgpt-ui-client:/home/chatgpt-ui-client"

系统直接报500错误，求助

**Comment by WongSaang** [comment]
添加环境变量：DEBUG=True

然后看日志

**Comment by 278213568** [comment]
> 添加环境变量：DEBUG=True
> 
> 然后看日志
DEBUG=True 添加到哪里呢？

**Comment by WongSaang** [comment]
![image](https://user-images.githubusercontent.com/46235412/231968110-3c86b59a-5e7e-41ae-94c1-ad25f6ccd291.png)

**Comment by 278213568** [comment]
添加了Debug=true
NotSupportedError at /admin/
MariaDB 10.3 or later is required (found 5.5.68).
是不是说明 MariaDB 版本低？

**Comment by WongSaang** [comment]
5.7

**Comment by 278213568** [comment]
好的， 谢谢
