### ISSUE TITLE
后台登录出现403

### ISSUE THREAD

**Issue by harochen75** [WongSaang/chatgpt-ui#117]
Forbidden (403)
CSRF verification failed. Request aborted.

**Comment by j704794464** [comment]
我也遇到了，这个是因为刚开始设置ip的时候设置了默认的localhost，这样的话只能在本地访问，通过IP访问的时候就会无法通过跨域访问的校验。搭建网站的时候输入你访问服务器使用的IP或者域名，就解决了。

**Comment by WongSaang** [comment]
If not yet resolved, please read these issues first: https://github.com/WongSaang/chatgpt-ui/issues?q=is%3Aissue+CSRF+
