### ISSUE TITLE
最新版本网页缩小后新建对话按钮消失，导致无法新建聊天影响使用，尽快修复（匹配问题，建议多测试）

### ISSUE THREAD

**Issue by luowei729** [WongSaang/chatgpt-ui#118]
![image](https://user-images.githubusercontent.com/10611605/229810439-600910fd-36a3-4ac3-8e8c-f0801e3a8844.png)

**Comment by luowei729** [comment]
手机打开也会确少新建聊天按钮，尽快修复

**Comment by WongSaang** [comment]
已修复
