### ISSUE TITLE
前端页面无法打开

### ISSUE THREAD

**Issue by eyefiy** [WongSaang/chatgpt-ui#119]
后端能进，设置了API Key

前端界面显示

Not Found

The requested resource was not found on this server.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/129654218/230112162-39651f30-37de-4b21-a81b-eb5890522e6d.png">

**Comment by WongSaang** [comment]
看起来是客户端容器没启动成功，能提供更多客户端容器的日志吗？
