### ISSUE TITLE
Web search missing in latest release. 

### ISSUE THREAD

**Issue by spencerwongfeilong** [WongSaang/chatgpt-ui#120]
In the latest release, not possible to perform with web search any more.

**Comment by WongSaang** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/46235412/230316659-4c760076-f17e-4e07-bcd8-54886daaab68.png)

**Comment by GOvEy1nw** [comment]
I believe this is still prevalent. Though it seems to come back too. 

This is the sequence of events:

Log-in, web search is missing
Close tab, go to it on a new tab, and it's back.

If I log out, close tab, and then log back in, web search is missing again.

**Comment by WongSaang** [comment]
> I believe this is still prevalent. Though it seems to come back too.
> 
> This is the sequence of events:
> 
> Log-in, web search is missing Close tab, go to it on a new tab, and it's back.
> 
> If I log out, close tab, and then log back in, web search is missing again.

@GOvEy1nw Fixed: https://github.com/WongSaang/chatgpt-ui/releases/tag/v2.4.6
