### ISSUE TITLE
SSR模式修改docker容器内的js文件后，工作不正常，如何解决

### ISSUE THREAD

**Issue by luowei729** [WongSaang/chatgpt-ui#122]
![image](https://user-images.githubusercontent.com/10611605/230347891-7d2af844-3d61-452a-ba4e-fc766abb81bf.png)

**Comment by WongSaang** [comment]
修改了哪里？怎么不正常？

**Comment by luowei729** [comment]
chatgpt说可以开启SSR框架的热更新功能，实现自动重新渲染，是否能够解决这个问题

**Comment by luowei729** [comment]
修改聊天页的任何提示性文字都会导致出问题
![image](https://user-images.githubusercontent.com/10611605/230349217-d9a3a4a5-d169-4c2e-b9f6-526e05dbd34a.png)

**Comment by luowei729** [comment]
> chatgpt说可以开启SSR框架的热更新功能，实现自动重新渲染，是否能够解决这个问题



> 修改了哪里？怎么不正常？

![image](https://user-images.githubusercontent.com/10611605/230349483-09a2c769-1784-4999-a5cd-afecae3b7378.png)
修改主页的任何文字都会出问题

**Comment by WongSaang** [comment]
建议修改源码后构建

**Comment by luowei729** [comment]
> 建议修改源码后构建

构建是否要搭建环境，没看到wiki上有相关构建教程

**Comment by WongSaang** [comment]
拉取项目到本地，修改后直接 docker build
