### ISSUE TITLE
response speed of chatgpt ui

### ISSUE THREAD

**Issue by spencerwongfeilong** [WongSaang/chatgpt-ui#128]
from @cgofun

The response speed of the chat is very slow and the real-time performance is poor. It takes several tens of seconds for the AI to reply. The API request speed test is not slow. What could be the reason for this?

**Comment by spencerwongfeilong** [comment]
I have the same observation. The speed of chatgpt ui generating the text is alot slower than other similar projects on github. 

I also light to point out that if the generated text is massive, there is a tendency that the text will drop out and cause a connecton closed error.

**Comment by luowei729** [comment]
srs会增加大量的内存占用，检查你的机器内存是不是爆了

**Comment by spencerwongfeilong** [comment]
Hello

I have more than enough resources running docker. 

![image](https://user-images.githubusercontent.com/127573355/230699176-d8102110-1429-4ec1-9eda-14473a1408ba.png)
![image](https://user-images.githubusercontent.com/127573355/230699205-963636b7-cd02-4ee6-9ee9-9518c64bdd1b.png)
![image](https://user-images.githubusercontent.com/127573355/230699227-de3b96f6-aa13-4091-b359-c33450e5871b.png)

**Comment by cgofun** [comment]
I am also experiencing slow AI response times, not due to resource issues. The UI loads quickly, but the AI response time is very slow, not just a little slow. It can take several tens of seconds or even longer, which makes exploration difficult.

**Comment by luowei729** [comment]
尝试kill   node server/index.mjs  这个进程试试，目前发现这个进程可能会有内存泄漏现象

**Comment by spencerwongfeilong** [comment]
> 尝试kill node server/index.mjs 这个进程试试，目前发现这个进程可能会有内存泄漏现象

Can you share with me where should I execute the command "kill node server/index.mjs"

In wsgi container console?

**Comment by spencerwongfeilong** [comment]
> 尝试kill node server/index.mjs 这个进程试试，目前发现这个进程可能会有内存泄漏现象

![image](https://user-images.githubusercontent.com/127573355/230704151-7da322d3-5e64-4591-b8f7-34f73bcc1d8b.png)

Do u mean like this? Did i execute the commands correctly. According to chatgpt i did =D

I executed the commands in the chatgpt-ui-client

**Comment by luowei729** [comment]
> 

kill this ，这个进程会自动重启，看能不能解决这个问题

**Comment by spencerwongfeilong** [comment]
I asked chatGPT and got this result. =D

![image](https://user-images.githubusercontent.com/127573355/230707836-cea20d97-18d6-4521-b742-f0195395d344.png)

**Comment by cgofun** [comment]
> > 
> 
> kill this ，这个进程会自动重启，看能不能解决这个问题

杀这个进程试过了，没有什么变化

**Comment by WongSaang** [comment]
This issue may be caused by node's proxy, which previously used nginx to proxy backend requests.

**Comment by WongSaang** [comment]
🤪Please help to test!
Temporarily switch the client image to this `wongsaang/chatgpt-ui-client:test` to see if it can solve this issue.

**Comment by spencerwongfeilong** [comment]
> 🤪Please help to test! Temporarily switch the client image to this `wongsaang/chatgpt-ui-client:test` to see if it can solve this issue.

hello. the client is still slow

**Comment by cgofun** [comment]
Around 8am, just before I sent this message, I tested the conversation and the response time was within a few seconds, which appeared to be normal. This suggests that it may be related to a busy period of the OpenAI official interface. My server is only being used by me, but it still feels slower compared to other clients that I have deployed. I think this may be related to the effectiveness of the AI's responses, as they appear almost instantly instead of dynamically appearing like a typing machine.

**Comment by cgofun** [comment]
https://user-images.githubusercontent.com/7732886/231025569-67f4d1bc-306f-4dc8-84a5-805eff9463db.mp4

**Comment by WongSaang** [comment]
> **VS**

If I understand correctly, Chatbot UI should be pure front-end, directly requesting openai's API. However, for the purpose of implementing multiple users, this project added a server-side layer. This extra layer means that it may be a bit slower than Chatbot UI.

**Comment by WongSaang** [comment]
> The name of each conversation is "Untitled Conversation", why?

Do you have any better suggestions?

**Comment by cgofun** [comment]
> > The name of each conversation is "Untitled Conversation", why?
> 
> Do you have any better suggestions?

Actually, this work is already excellent, and the response speed is much better than before. Regarding the session title, I just wanted to offer a suggestion that generating an automatic summary title, like ChatGPT, would be better. Additionally, it would be ideal if the "frugal mode" could be controlled by a backend parameter to determine whether it is enabled or not.

**Comment by yblisss** [comment]
+1 for frugal mode :)

**Comment by WongSaang** [comment]
> +1 for disable by default frugal mode :)

You can now turn it off in the admin pannel 
https://wongsaang.github.io/chatgpt-ui/guide/configuration.html#frugal-mode-control

**Comment by yblisss** [comment]
> > +1 for disable by default frugal mode :)
> 
> You can now turn it off in the admin pannel https://wongsaang.github.io/chatgpt-ui/guide/configuration.html#frugal-mode-control

Oh thanks !!!! :)
