### ISSUE TITLE
已经解决了之前的一系列问题，但是最后询问的时候还是报错。已经正确添加了API

### ISSUE THREAD

**Issue by OYLFLMH** [WongSaang/chatgpt-ui#13]
![20230304172411](https://user-images.githubusercontent.com/95945448/222890585-a8d8e011-f338-47d3-92d9-e78a6a0f41aa.png)

**Comment by OYLFLMH** [comment]
重点要感谢你的分享，谢谢了。

**Comment by WongSaang** [comment]
🧱墙内已经无法请求API啦~
最好能部署在墙外

**Comment by OYLFLMH** [comment]
收到， 谢谢了，如果只是这个原因， 我就好解决了。

**Comment by OYLFLMH** [comment]
是否我在部署的服务器上再部署VPN 科学上网，就能解决问题了？

**Comment by OYLFLMH** [comment]
Failed to send message. HTTP 200 - OK ,
重新部署VPN 后，报错变成这个了。。。

**Comment by WongSaang** [comment]
写了一个 shell 脚本，可以直接部署到 vps 上，看 Readme

**Comment by OYLFLMH** [comment]
谢谢你的回复，我刚才做了全局VPN调试，同时看了docker日志，重新部署后，API已经没有报错了。但是输入文字后，立刻出现截图的报错，之前所有报错都要等，这个报错是秒出。
![1120230304235026](https://user-images.githubusercontent.com/95945448/222915837-e40ab946-c525-43bc-844d-df623d680e3d.png)

**Comment by OYLFLMH** [comment]
好的， 我重新按您新的脚本部署测试一下，谢谢。

**Comment by WongSaang** [comment]
管理面板能访问吗？需要登录管理面板设置一个api key

**Comment by OYLFLMH** [comment]
再次谢谢你，一切都正常，API ，管理界面，连接openAI网站，设置，我都搞定了，但是还是报Failed to send message. HTTP 500 - Internal Server Error，我认为唯一和您不同的地方， 就是我是用Centos7.9 2009 部署的。其他我想不出有什么问题，你这边可以远程帮我看看吗？
![image](https://user-images.githubusercontent.com/95945448/222938185-2694ec9c-f5f2-484f-bc90-fc0ba9e10422.png)
![image](https://user-images.githubusercontent.com/95945448/222938276-ffd6cff5-bc98-4be2-8c8a-6852f578eb58.png)

**Comment by WongSaang** [comment]
给我留个邮箱

**Comment by OYLFLMH** [comment]
44478807@qq.com
现在报错又变成了秒出的  Failed to send message. HTTP 400 - Bad Request 。

[root@localhost chatgpt-ui]# curl -I https://api.openai.com
HTTP/1.1 200 Connection established

curl: (35) TCP connection reset by peer
这个连接是正常的吗？如果确实是被拒绝，我再修改。

**Comment by OYLFLMH** [comment]
之前的日志，看到有api.openai.com的报错 ，但是现在日志没看到有报错
chatgpt-ui-backend-wsgi-server-1  | 2023-03-05T03:44:29.863044569Z 172.18.0.3 - - [05/Mar/2023:03:44:29 +0000] "POST /api/conversation/ HTTP/1.0" 400 53 "http://192.168.1.67/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
chatgpt-ui-client-1               | 2023-03-05T03:44:29.863133707Z 192.168.1.62 - - [05/Mar/2023:03:44:29 +0000] "POST /api/conversation/ HTTP/1.1" 400 53 "http://192.168.1.67/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
chatgpt-ui-backend-web-server-1   | 2023-03-05T03:44:29.863042871Z 172.18.0.4 - - [05/Mar/2023:03:44:29 +0000] "POST /api/conversation/ HTTP/1.0" 400 53 "http://192.168.1.67/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "192.168.1.62"
chatgpt-ui-backend-wsgi-server-1  | 2023-03-05T03:45:30.618874615Z 172.18.0.3 - - [05/Mar/2023:03:45:30 +0000] "POST /api/conversation/ HTTP/1.0" 400 53 "http://192.168.1.67/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
chatgpt-ui-backend-web-server-1   | 2023-03-05T03:45:30.618982023Z 172.18.0.4 - - [05/Mar/2023:03:45:30 +0000] "POST /api/conversation/ HTTP/1.0" 400 53 "http://192.168.1.67/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "192.168.1.62"
chatgpt-ui-client-1               | 2023-03-05T03:45:30.618988258Z 192.168.1.62 - - [05/Mar/2023:03:45:30 +0000] "POST /api/conversation/ HTTP/1.1" 400 53 "http://192.168.1.67/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"

**Comment by WongSaang** [comment]
你好，可能使用代理还是连接不上 openai 哦，这是正常的情况：
![image](https://user-images.githubusercontent.com/46235412/222940900-aa7e2255-5ead-44ed-baeb-df0b795aa2bb.png)

你可以看看这个方案去配置一个代理，[https://github.com/noobnooc/noobnooc/discussions/9](https://github.com/noobnooc/noobnooc/discussions/9), 
然后在 `backend-wsgi-server` 这个容器中增加一个环境变量 `OPENAI_API_PROXY=http://proxy` 来使用代理

**Comment by OYLFLMH** [comment]
测试已经连上了。
![image](https://user-images.githubusercontent.com/95945448/222943662-5879289c-6ae5-4d03-98aa-344a91b1337f.png)
但是仍然报400错误，而且我输入的消息，在9000的管理后台看不到。感觉直接被程序拒绝没有输出到chatGPT.之前虽然报500错误，但是可以在管理页面的message看到我曾经发的消息。
![image](https://user-images.githubusercontent.com/95945448/222943726-96d94f3a-e2b3-40a0-a307-65453e4e9c52.png)
![image](https://user-images.githubusercontent.com/95945448/222943781-c5a5ef43-fc02-403d-b4aa-5f6ce6532e5a.png)

**Comment by OYLFLMH** [comment]
![image](https://user-images.githubusercontent.com/95945448/222943850-f7ebd084-f84c-4ae7-b916-62532afc0125.png)

**Comment by WongSaang** [comment]
这个改成小写看看
![image](https://user-images.githubusercontent.com/46235412/222943958-57418381-cfd3-415a-b906-12a7cab8132c.png)

**Comment by OYLFLMH** [comment]
晕死， 改了小写，重启docker compose up -d,看到信息了。
![image](https://user-images.githubusercontent.com/95945448/222944099-16f50e2f-5bb1-46f0-85f8-90fa75da5453.png)
但是又开始报502 错误 和 500 错误。

**Comment by OYLFLMH** [comment]
又一个重要因素会不会影响，本机有双网卡，内网和外网，外网有网关和DNS，需要对docker网络做什么设置吗？
![image](https://user-images.githubusercontent.com/95945448/222945158-419511de-ba05-4f82-97bc-d2a46948c92b.png)
![image](https://user-images.githubusercontent.com/95945448/222945168-d600962b-d669-4989-8d80-1adb251c7671.png)

**Comment by WongSaang** [comment]
看看 docker compose 的请求日志，对症下药

**Comment by OYLFLMH** [comment]
[日志.txt](https://github.com/WongSaang/chatgpt-ui/files/10890951/default.txt)

**Comment by OYLFLMH** [comment]
你可以远程向日葵看看也行.

**Comment by WongSaang** [comment]
![image](https://user-images.githubusercontent.com/46235412/222946385-445fd51f-f710-4d1c-bdb1-500b22bf0313.png)
你的网还是请求不到 api.openai.com, 实在需要用，还是建议这个方式：https://github.com/WongSaang/chatgpt-ui/issues/13#issuecomment-1454984319

**Comment by WongSaang** [comment]
怎么样？解决了吗？如果没有别的问题，我就把这个 Issue 关闭😀

**Comment by OYLFLMH** [comment]
谢谢了，可以关闭的。

Wong Saang ***@***.***> 于2023年3月8日周三 23:29写道：
