### ISSUE TITLE
提一个小建议

### ISSUE THREAD

**Issue by KevinJonesChs** [WongSaang/chatgpt-ui#131]
django admin 后台太丑，可以用django-simpleui 这个给美化一下，哈哈
pip install django-simpleui
在settings 的app 里边添加
simpleui 就可以了

**Comment by luowei729** [comment]
后台无关紧要，前台搞好看点更有意义

**Comment by WongSaang** [comment]
@KevinJonesChs 感谢建议，已更新：https://github.com/WongSaang/chatgpt-ui-server/releases/tag/v2.4.2
