### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by zonbao** [WongSaang/chatgpt-ui#132]
start with Docker Compose, and get an error when i try to login the administration panel

Forbidden (403)
CSRF verification failed. Request aborted.
More information is available with DEBUG=True.

**Comment by OYLFLMH** [comment]
是因为你白名单设置不对，要不就在这里填入你的服务器地址。
 - APP_DOMAIN=${APP_DOMAIN:-localhost:9000}
 把localhost换成你的服务器本地地址。

**Comment by Androsyn31** [comment]
I have the same probleme, my environnement is ${APP_DOMAIN:-https://mydomain.com:9000}

**Comment by WongSaang** [comment]
Please search for related issues as there are already many solutions available in this regard.
