### ISSUE TITLE
当使用iframe将网页嵌入到其他网站页面内时，无法登陆

### ISSUE THREAD

**Issue by tsingchou** [WongSaang/chatgpt-ui#134]
当使用iframe将网页嵌入到其他网站页面内时，无法运行，点击登录后一闪而过跳回登录页面，返回401，是否有办法避免这个问题

**Comment by WongSaang** [comment]
iframe 如果跨域的话不会发送 cookie，可以试试 nginx 反向代理使用同一个域名

**Comment by tsingchou** [comment]
嗯，放弃iframe，重写了前端，httpd.conf中写了PassProxy解决了问题。如果后端的接口
有docs就更方便啦

发自我的 iPhone

在 2023年4月11日，20:22，Wong Saang ***@***.***> 写道：

﻿

iframe 如果跨域的话不会发送 cookie，可以试试 nginx 反向代理使用同一个域名

**Comment by WongSaang** [comment]
精力有限，可以参考前端请求
