### ISSUE TITLE
Supports less length than official playground?

### ISSUE THREAD

**Issue by pbjorklund** [WongSaang/chatgpt-ui#140]
When I give it 50-100 sentences it complains about being over token limit even though the playground happily swallows it. GPT4 model with tokens cranked to the max

**Comment by WongSaang** [comment]
Hello, thank you very much for your feedback.

In the previous version, the available `prompt_tokens` was not calculated based on the `max_tokens` parameter passed in from the front-end. This was probably the reason for the issue. It has now been fixed. Please pull the latest wsig-server image and try again.
