### ISSUE TITLE
后台 setting 里面， openai_api_key 可以设置多个吗？

### ISSUE THREAD

**Issue by 278213568** [WongSaang/chatgpt-ui#149]

**Comment by WongSaang** [comment]
设置多个，每次使用的选择策略是什么呢？

**Comment by 278213568** [comment]
> 设置多个，每次使用的选择策略是什么呢？

--：如果是多个， 内部设定每个每天使用的次数， 这样的话， 就可以平衡一下每一个key 每天均衡的使用。

**Comment by WongSaang** [comment]
请更新到最新版本并查看说明：https://wongsaang.github.io/chatgpt-ui/zh/guide/quick-start.html#%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E4%B9%8B%E5%90%8E
