### ISSUE TITLE
Got 'CSRF verification failed. Request aborted.' when accessing admin panel after docker deployment

### ISSUE THREAD

**Issue by xiaoquqi** [WongSaang/chatgpt-ui#15]
I use docker-compose.yml to deploy this project, I only change the client port from 80 to 10080 as my 80 is already in used.

```
    ports:
      - '10080:80'
```

After run docker-compose.yml, I use my browser to access the admin panel from remote(not localhost). Then I got 'CSRF verification failed. Request aborted' after login with username and password.

![image](https://user-images.githubusercontent.com/127915/223091176-5948127c-eb89-4491-94c5-81f21ff28211.png)

**Comment by OYLFLMH** [comment]
![image](https://user-images.githubusercontent.com/95945448/223096270-ff6ea4d8-7d15-491c-9798-7ed9d8a76712.png)
My deployment results were the same, and I had to add the host address here to make it work.

**Comment by xiaoquqi** [comment]
Yes, after changed to my real ip in APP_DOMAIN, it fixed. Would you like to update README to clarify this?
