### ISSUE TITLE
网页搜索小bug！

### ISSUE THREAD

**Issue by unrulpkk** [WongSaang/chatgpt-ui#154]
如果后台设备搜索设置打开，第一次注册登录成功之后，没有搜索选项！要刷新一次才能看到搜索选项。

问个技术问题，聊天界面的字体太大了，要怎么设置字体？

**Comment by WongSaang** [comment]
关于字体的问题，可以看下组件库文档 https://vuetifyjs.com/en/

**Comment by WongSaang** [comment]
> 如果后台设备搜索设置打开，第一次注册登录成功之后，没有搜索选项！要刷新一次才能看到搜索选项。

@unrulpkk 最新版已修复这个问题
