### ISSUE TITLE
管理后台无法打开

### ISSUE THREAD

**Issue by 278213568** [WongSaang/chatgpt-ui#162]
docker-compose logs 如下， 但是管理后台无法打开， connect timeout
Attaching to mars_client_1, mars_backend-web-server_1, mars_backend-wsgi-server_1
backend-wsgi-server_1  | Operations to perform:
backend-wsgi-server_1  |   Apply all migrations: account, admin, auth, chat, contenttypes, provider, sessions, sites, socialaccount, stats
backend-wsgi-server_1  | Running migrations:
backend-wsgi-server_1  |   Applying contenttypes.0001_initial... OK
backend-wsgi-server_1  |   Applying auth.0001_initial... OK
backend-wsgi-server_1  |   Applying account.0001_initial... OK
backend-wsgi-server_1  |   Applying account.0002_email_max_length... OK
backend-wsgi-server_1  |   Applying admin.0001_initial... OK
backend-wsgi-server_1  |   Applying admin.0002_logentry_remove_auto_add... OK
backend-wsgi-server_1  |   Applying admin.0003_logentry_add_action_flag_choices... OK
backend-wsgi-server_1  |   Applying contenttypes.0002_remove_content_type_name... OK
backend-wsgi-server_1  |   Applying auth.0002_alter_permission_name_max_length... OK
backend-wsgi-server_1  |   Applying auth.0003_alter_user_email_max_length... OK
backend-wsgi-server_1  |   Applying auth.0004_alter_user_username_opts... OK
backend-wsgi-server_1  |   Applying auth.0005_alter_user_last_login_null... OK
backend-wsgi-server_1  |   Applying auth.0006_require_contenttypes_0002... OK
backend-wsgi-server_1  |   Applying auth.0007_alter_validators_add_error_messages... OK
backend-wsgi-server_1  |   Applying auth.0008_alter_user_username_max_length... OK
backend-wsgi-server_1  |   Applying auth.0009_alter_user_last_name_max_length... OK
backend-wsgi-server_1  |   Applying auth.0010_alter_group_name_max_length... OK
backend-wsgi-server_1  |   Applying auth.0011_update_proxy_permissions... OK
backend-wsgi-server_1  |   Applying auth.0012_alter_user_first_name_max_length... OK
backend-wsgi-server_1  |   Applying chat.0001_initial... OK
backend-wsgi-server_1  |   Applying chat.0002_message... OK
backend-wsgi-server_1  |   Applying chat.0003_setting... OK
backend-wsgi-server_1  |   Applying chat.0004_prompt... OK
backend-wsgi-server_1  |   Applying chat.0005_remove_message_parent_message... OK
backend-wsgi-server_1  |   Applying chat.0006_add_prompt_title... OK
backend-wsgi-server_1  |   Applying chat.0007_message_messages_message_tokens... OK
backend-wsgi-server_1  |   Applying provider.0001_initial... OK
backend-wsgi-server_1  |   Applying sessions.0001_initial... OK
backend-wsgi-server_1  |   Applying sites.0001_initial... OK
backend-wsgi-server_1  |   Applying sites.0002_alter_domain_unique... OK
backend-wsgi-server_1  |   Applying socialaccount.0001_initial... OK
backend-wsgi-server_1  |   Applying socialaccount.0002_token_max_lengths... OK
backend-wsgi-server_1  |   Applying socialaccount.0003_extra_data_default_dict... OK
backend-wsgi-server_1  |   Applying stats.0001_initial... OK
backend-wsgi-server_1  | Setting up default settings...
backend-wsgi-server_1  | Created setting: openai_api_key
backend-wsgi-server_1  | Created setting: open_registration
backend-wsgi-server_1  | Created setting: open_web_search
backend-wsgi-server_1  | Created setting: open_api_key_setting
backend-wsgi-server_1  | Superuser created successfully.
backend-wsgi-server_1  | [2023-04-18 00:52:02 +0000] [1] [INFO] Starting gunicorn 20.1.0
backend-wsgi-server_1  | [2023-04-18 00:52:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend-wsgi-server_1  | [2023-04-18 00:52:02 +0000] [1] [INFO] Using worker: sync
backend-wsgi-server_1  | [2023-04-18 00:52:02 +0000] [8] [INFO] Booting worker with pid: 8
backend-wsgi-server_1  | [2023-04-18 00:52:02 +0000] [9] [INFO] Booting worker with pid: 9
backend-wsgi-server_1  | [2023-04-18 00:52:02 +0000] [10] [INFO] Booting worker with pid: 10
client_1               | Listening http://[::]:80
backend-web-server_1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
backend-web-server_1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
backend-web-server_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
backend-web-server_1   | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
backend-web-server_1   | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
backend-web-server_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
backend-web-server_1   | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
backend-web-server_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
backend-web-server_1   | /docker-entrypoint.sh: Configuration complete; ready for start up
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: using the "epoll" event method
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: nginx/1.22.1
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4)
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: OS: Linux 3.10.0-1062.12.1.el7.x86_64
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: start worker processes
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: start worker process 34
backend-web-server_1   | 2023/04/18 00:51:58 [notice] 1#1: start worker process 35

**Comment by 278213568** [comment]
http://47.241.5.241:9000/admin
Connection to 47.241.5.241 Failed

**Comment by WongSaang** [comment]
日志看起来没问题，看起来是网络的问题。9000 端口打开了吗？看看安全组配置是否打开了这个端口

**Comment by 278213568** [comment]
> 日志看起来没问题，看起来是网络的问题。9000 端口打开了吗？看看安全组配置是否打开了这个端口

确实是这个问题， 多谢
