### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by nick-harder** [WongSaang/chatgpt-ui#164]
Hi there, great app, and I am trying to use it. I am hosting it on my v-server with the linked voice2gpt.de domain and use the docker for the the installation. I can access the admin panel, but I cannot login as user. The registration function doesn't work as it requests an invitation code, but I don't understand where to find it. Also, if I add user manually from the admin panel, I still cannot log in, as it return an "Something went wrong. Please try again" error. Please help!

here is the docker-compose.yml config I used:
`
version: '3'
services:
  client:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=https://voice2gpt.de
      - DEFAULT_LOCALE=en
      - NUXT_PUBLIC_APP_NAME='ChatGPT UI' # The name of the application
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_ui_network
    restart: always
  backend-wsgi-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - APP_DOMAIN=voice2gpt.de:9000
      - SERVER_WORKERS=3 # The number of worker processes for handling requests.
      - WORKER_TIMEOUT=180 # Workers silent for more than this many seconds are killed and restarted. default 180s
      - DB_URL=${DB_URL:-sqlite:///db.sqlite3} # If this parameter is not set, the built-in Sqlite will be used by default. It should be noted that if you do not connect to an external database, the data will be lost after the container is destroyed.
      - DJANGO_SUPERUSER_USERNAME=admin # default superuser name
      - DJANGO_SUPERUSER_PASSWORD=password # default superuser password
      - DJANGO_SUPERUSER_EMAIL=nick.harder.ai@gmail.com # default superuser email
      - ACCOUNT_EMAIL_VERIFICATION=none # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
    ports:
      - '${WSGI_PORT:-8000}:8000'
    networks:
      - chatgpt_ui_network
    restart: always
  backend-web-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always

networks:
  chatgpt_ui_network:
    driver: bridge
`

**Comment by WongSaang** [comment]
Hello, I just tried your link and it is working for login.

**Comment by WongSaang** [comment]
You can log in directly with the admin account.

**Comment by WongSaang** [comment]
Please modify your docker-compose.yml

```
image: wongsaang/chatgpt-ui-client:latest
environment:
      - SERVER_DOMAIN=http://backend-web-server
```

Or if Your front-end and back-end containers are not on the same network.

```
image: wongsaang/chatgpt-ui-client:latest
environment:
      - SERVER_DOMAIN=https://voice2gpt.de:9000
```

**Comment by nick-harder** [comment]
thanks! I will try that. Loving the app sofar, thanks a lot for it! Another question, is there any documentation how the web search function works? would love to read about it. If it is not in English, it is fine, I will translate it

**Comment by WongSaang** [comment]
I'm sorry, there are currently no related documents available. I can provide a simple idea:
1. The backend program will use the user's input to search on duckduckgo.com
2. Extract the search results and generate prompt
3. Send the prompt to ChatGPT

If you are interested, you can take a look at the source code in the server-side project https://github.com/WongSaang/chatgpt-ui-server .
