### ISSUE TITLE
打开后台 ， 出现 502 Bad Gateway

### ISSUE THREAD

**Issue by 278213568** [WongSaang/chatgpt-ui#165]
打开后台 ， 出现 502 Bad Gateway,  看docker-compose logs有如下：
connect() failed (111: Connection refused) while connecting to upstream, client: 118.163.116.68, server: localhost, request: "GET /admin/ HTTP/1.0", upstream: "http://192.168.48.2:8000/admin/", host: "47.241.5.241:9000"

**Comment by 278213568** [comment]
什么都没有修改， 为什么又好了？ 后台又能正常访问了。

**Comment by WongSaang** [comment]
可能是当时容器没完全启动，目前还有这个问题吗？

**Comment by 278213568** [comment]
目前没有这个问题了， 但是我看容器启动日志里面也正常的。搞不懂了。

**Comment by WongSaang** [comment]
如再遇到随时打开
