### ISSUE TITLE
数学公式渲染

### ISSUE THREAD

**Issue by godv23** [WongSaang/chatgpt-ui#168]
大佬可以增加对数学公式的支持吗？
![image](https://user-images.githubusercontent.com/71914458/232740290-a93881a4-ad6e-49a4-8bca-68d57986b96a.png)

**Comment by WongSaang** [comment]
🤪 懒得输入，可以把你图片里的内容复制给我吗？

**Comment by godv23** [comment]
> 🤪 懒得输入，可以把你图片里的内容复制给我吗？

我们可以使用马尔可夫过程来解决这个问题。定义状态 $i$ 表示当前的等级为 $i$，包括 $i=0,1,2,3,4$。我们的目标是求出从状态 $0$ 开始，第一次到达状态 $4$ 的期望步数。

首先，我们可以列出状态转移矩阵 $P$：

$$ P = \begin{bmatrix} 1/3 & 1/3 & 1/3 & 0 & 0 \ 1/3 & 1/3 & 1/3 & 0 & 0 \ 1/3 & 1/3 & 1/3 & 0 & 0 \ 1/3 & 0 & 0 & 1/3 & 1/3 \ 1/3 & 0 & 0 & 1/3 & 1/3 \end{bmatrix} $$

其中 $P_{i,j}$ 表示从状态 $i$ 转移到状态 $j$ 的概率。注意到当玩家到达状态 $4$ 时，状态会回到 $0$，因此 $P_{4,0}=1$。

接下来，我们可以列出转移概率的矩阵 $Q$，其中 $Q_{i,j}$ 表示从状态 $i$ 转移到状态 $j$ 的概率，但不包括从状态 $4$ 回到状态 $0$：

$$ Q = \begin{bmatrix} 1/3 & 1/3 & 1/3 & 0 \ 1/3 & 1/3 & 1/3 & 0 \ 1/3 & 1/3 & 1/3 & 0 \ 1/3 & 0 & 0 & 1/3 \end{bmatrix} $$

现在我们可以计算出从状态 $i$ 开始，第一次到达状态 $4$ 的期望步数 $T_i$。根据全期望公式，有：

$$ T_i = 1 + \sum_{j\neq i} Q_{i,j} T_j $$

其中 $1$ 表示从状态 $i$ 到状态 $4$ 的一步，$\sum_{j\neq i} Q_{i,j} T_j$ 表示从状态 $i$ 转移到其他状态 $j$ 的概率之和乘以从状态 $j$ 开始，第一次到达状态 $4$ 的期望步数。

我们可以使用线性方程组求解 $T_i$，其中 $i=0,1,2,3$。最终的答案是 $T_0$，即从状态 $0$ 开始，第一次到达状态 $4$ 的期望步数。

$$ \begin{cases} T_0 = 1 + \frac{1}{3} T_0 + \frac{1}{3} T_1 + \frac{1}{3} T_2 \ T_1 = 1 + \frac{1}{3} T_0 + \frac{1}{3} T_1 + \frac{1}{3} T_2 \ T_2 = 1 + \frac{1}{3} T_0 + \frac{1}{3} T_1 + \frac{1}{3} T_2 \ T_3 = 1 + \frac{1}{3} T_0 \end{cases} $$

解得 $T_0 = \frac{243}{32}$，因此玩家从0级升到4级的期望是 $\frac{243}{32}$ 步。

**Comment by godv23** [comment]
> 🤪 懒得输入，可以把你图片里的内容复制给我吗？

被渲染了  我给你复制一行吧
【
$$ P = \begin{bmatrix} 1/3 & 1/3 & 1/3 & 0 & 0 \ 1/3 & 1/3 & 1/3 & 0 & 0 \ 1/3 & 1/3 & 1/3 & 0 & 0 \ 1/3 & 0 & 0 & 1/3 & 1/3 \ 1/3 & 0 & 0 & 1/3 & 1/3 \end{bmatrix} $$
】

**Comment by WongSaang** [comment]
已支持，请更新到最新版本。
