### ISSUE TITLE
请教怎样开启HTTPS访问

### ISSUE THREAD

**Issue by zoubei** [WongSaang/chatgpt-ui#17]
为了开启HTTPS访问，我计划使用nginx反向代理。客户端页面需要让出80端口，我尝试将docker-compose.yml中client的ports改为'81:80'。原来的页面加:81端口访问，但原页面好像无法正常使用了，请问我改端口的方法对吗？或者还有其他的方法添加SSL证书开启HTTPS？

ps:很棒的客户端，感谢分享！

**Comment by WongSaang** [comment]
感谢反馈和鼓励 ❤️
1. 理论上修改端口是不会影响的，可以看看容器的日志，有的话可以贴上来。
2. 如果部署在服务器上，推荐使用 cloudflare.com 作为代理，他们提供免费证书，这样就不需要自己配置：
![image](https://user-images.githubusercontent.com/46235412/223390986-5b6ffdd4-8707-463a-9d57-d340882cc21a.png)

**Comment by zoubei** [comment]
感谢回复！
对了，cloudflare就有免费的HTTPS功能，我以前还用过，马上去弄

**Comment by WongSaang** [comment]
如果没有其他问题，这个 Issue 关闭咯？
