### ISSUE TITLE
docker build 后无法使用

### ISSUE THREAD

**Issue by mustang2247** [WongSaang/chatgpt-ui#18]
docker build --target wsgi-server -t chatgpt-server-wsgi-server:latest .

docker run --rm -p 9000:8000 chatgpt-server-wsgi-server:latest

报错：
exec ./entrypoint.sh: no such file or directory

**Comment by WongSaang** [comment]
https://github.com/WongSaang/chatgpt-ui-server/issues/2#issuecomment-1459818335

**Comment by mustang2247** [comment]
收到
