### ISSUE TITLE
前端yarn dev后出现500页面错误

### ISSUE THREAD

**Issue by Y1hsiaochunnn** [WongSaang/chatgpt-ui#183]
如图
![image](https://user-images.githubusercontent.com/66012385/233910946-57f2e1b9-3176-497d-96ac-da245fb0b0c5.png)

**Comment by Lemmynjash** [comment]
I am getting the same error

**Comment by Y1hsiaochunnn** [comment]
I think we used the wrong version of nodejs, you can use the nodejs version manager to install a nodejs18, I successfully solved this problem



---原始邮件---
发件人: "Lemmy ***@***.***&gt;
发送时间: 2023年4月25日(周二) 凌晨2:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WongSaang/chatgpt-ui] 前端yarn dev后出现500页面错误 (Issue #183)




 
I am getting the same error

**Comment by Lemmynjash** [comment]
Awesome I upgraded my node -v to 19.0.0 and it worked thank you very much
