### ISSUE TITLE
客户端会产生text-davinci模型的请求

### ISSUE THREAD

**Issue by zoubei** [WongSaang/chatgpt-ui#20]
登录openai后台，发现产生了包括text-davinci模型的请求（好像是在新建会话时会产生），请排查下是否为bug。

如图：
![image](https://user-images.githubusercontent.com/28042090/223664931-3703f70f-cacf-4305-a794-bcb12db1ce18.png)

**Comment by WongSaang** [comment]
您好，目前的版本使用 `text-davinci` 来自动生成对话主题，就是左侧导航栏中的对话列表的标题。

欢迎提供更好的方案 ❤️

**Comment by zoubei** [comment]
哈哈，原来如此，或许主题也可以考虑通过gpt-3.5-turbo生成，因为据说价格只有1/10🤭

**Comment by WongSaang** [comment]
是的，尽快更新

**Comment by WongSaang** [comment]
已更新，请拉取最新镜像 wongsaang/chatgpt-ui-wsgi-server:latest

**Comment by zoubei** [comment]
这么快就更新了，太给力了。大大的赞🤭

**Comment by WongSaang** [comment]
🤪
