### ISSUE TITLE
能否使对话连续的输出

### ISSUE THREAD

**Issue by gdcurs** [WongSaang/chatgpt-ui#21]
大佬，能否使对话连续输出，即一个字一个字连续输出，而不是输出几行然后停止，等一会又输出几行。还有一个就是，如果网页后台了，输出就好像停止了，切换回来才会继续。

**Comment by WongSaang** [comment]
尽快安排

**Comment by WongSaang** [comment]
你好，由于这个问题：https://github.com/WongSaang/chatgpt-ui/issues/22#issue-1616912680 ，这涉及到效率问题，个人认为相对来说比显示效果重要，所以打字效果暂时在 v2.1.7 中取消。

后续版本中考虑增加一个配置来使用这种效果。

**Comment by WongSaang** [comment]
已增加环境变量来控制是否打开打字机效果，请看 readme

**Comment by gdcurs** [comment]
> 已增加环境变量来控制是否打开打字机效果，请看 readme

感谢大佬开发这个App

**Comment by ruotianluo** [comment]
你好请问怎么样通过环境变量来打开打字机效果？readme翻了好几遍好像也没看到。

**Comment by WongSaang** [comment]
你好，环境变量目前只在构建镜像时生效，你可以用docker 构建自己的版本

Ruotian(RT) Luo ***@***.***> 于 2023年4月3日周一 12:13写道：
