### ISSUE TITLE
输出代码太慢且样式错误

### ISSUE THREAD

**Issue by Luqijian** [WongSaang/chatgpt-ui#22]
大佬现在这种一字一字输出很不适合大段内容啊，尤其是代码，太磨蹭了。
而且代码输出过程中可能是没检测到markdown的```结束符，样式一直在跳动，跳完了样式也是错误的，没有代码上色

**Comment by WongSaang** [comment]
您好，感谢反馈。

最新的版本已经明显改善这个问题，请拉取最新镜像。

**Comment by Luqijian** [comment]
> 输出效率的问题好改，跳样式的问题有没什么好方案🙃

有在用这个项目：https://github.com/Chanzhaoyu/chatgpt-web。
他的方案看上去是普通文本跟代码的输出逻辑是分开的，普通文本是连续输出，但不是一个字而是几个字，代码就是整段输出，看上去很合理

**Comment by WongSaang** [comment]
感谢，我学习下

**Comment by Luqijian** [comment]
> 感谢，我学习下

还得感谢大佬开发这个网页App
