### ISSUE TITLE
貌似可以随意注册呢

### ISSUE THREAD

**Issue by tsingchou** [WongSaang/chatgpt-ui#23]
貌似可以随意注册呢，是否可以关闭注册功能

**Comment by tsingchou** [comment]
是否可以django admin中，设置开启/关闭帐户注册功能

**Comment by spencerwongfeilong** [comment]
https://stackoverflow.com/questions/61656796/how-do-i-set-a-user-as-inactive-in-django-when-registering

This seems to be a good solution. Setting user to be inactive after registration.

**Comment by WongSaang** [comment]
> https://stackoverflow.com/questions/61656796/how-do-i-set-a-user-as-inactive-in-django-when-registering
> 
> This seems to be a good solution. Setting user to be inactive after registration.

Thank you very much for your suggestion. However, as planned, I have already added the relevant setting in the admin panel to achieve the goal.

**Comment by WongSaang** [comment]
In the latest version, the `open_registration` setting option has been added in the admin panel to control whether user registration is enabled. You can log in to the admin panel and find this setting option under `Chat->Setting`. The default value of this setting is `True` (allow user registration). If you do not need it, please change it to `False`.

Please pull the latest image.


在最新的版本中，已在管理后台增加 `open_registration` 设置项，用于控制是否开放用户注册。
你可以登录管理后台，在 `Chat->Setting` 中看到这个设置项，默认是 `True` (允许用户注册)，如果不需要，请改成 `False`。

请拉取最新镜像。

**Comment by GOvEy1nw** [comment]
hi, I've set the value to 'False' but it doesn't appear to have done anything. Is it supposed to get rid of the 'create an account' button etc too or does it just disable actually saving registrations to the database?

**Comment by WongSaang** [comment]
This feature currently only prevents the creation of new users on the backend, but does not hide the registration button on the frontend. 
Sorry, due to limited time, we cannot improve this feature at the moment.
