### ISSUE TITLE
运行前端出现这个500报错怎么解决啊

### ISSUE THREAD

**Issue by ZhanyueZ** [WongSaang/chatgpt-ui#233]
感谢！

<img width="1265" alt="0f163c1480fe2926e4113f6dbda0a55" src="https://github.com/WongSaang/chatgpt-ui/assets/97413746/f50a9181-f060-4525-8a7e-f84883133972">

**Comment by caoshuailian** [comment]
请问你是如何解决的呀，我也有这个问题
