### ISSUE TITLE
Error when clicking the stop button

### ISSUE THREAD

**Issue by YuZhou23** [WongSaang/chatgpt-ui#3]
ctrl is not defined

![image](https://user-images.githubusercontent.com/125260237/218424179-d2186446-69f9-4b0d-8474-c9400bba791e.png)

**Comment by WongSaang** [comment]
Fixed: [fix error when clicking the stop button and optimize SSE logic](https://github.com/WongSaang/chatgpt-ui/commit/5201349363c9a5d13280b2879067d2d535cd3988)
