### ISSUE TITLE
一行命令部署到服务器 自定义端口号

### ISSUE THREAD

**Issue by Cp0204** [WongSaang/chatgpt-ui#31]
80和9000（Portainer）端口，和常用端口冲突。
除非全新部署设备，否则80基本都用的；一次跑不起来，要手动调，也就失去一键的意义了。

**Comment by Cp0204** [comment]
参考命令：
```
read -p "请输入端口号：" port

sed -i "s/:9000/:$port/g" docker-compose.yml
```

**Comment by WongSaang** [comment]
感谢反馈!

已更新 deployment.sh，支持在执行脚本时设置各服务端口

**Comment by Cp0204** [comment]
> 感谢反馈!
> 
> 已更新 deployment.sh，支持在执行脚本时设置各服务端口

感谢回复！赞！

**Comment by Cp0204** [comment]
新脚本安装报错：
```
Starting services...
unknown flag: --pull
Done
```

**Comment by WongSaang** [comment]
你的 docker 版本是最新的吗

**Comment by Cp0204** [comment]
> 你的 docker 版本是最新的吗

x86 20.10.16，刚换23.0.1可以了
