### ISSUE TITLE
Add Restart Policy

### ISSUE THREAD

**Issue by ilovefreesw** [WongSaang/chatgpt-ui#32]
Right now, the container will not start if I reboot the server. So, it would better if there is a restart policy in the `docker-compose.yml`.

https://serverfault.com/questions/884759/how-does-restart-always-policy-work-in-docker-compose

**Comment by WongSaang** [comment]
Hello,

Thank you for your feedback. 

The docker-compose.yml file has been updated and the latest version of docker-compose.yml now includes `restart: always` in each service. 

I'm not sure if this is the result you were looking for.

**Comment by ilovefreesw** [comment]
Yes that will do it!
