### ISSUE TITLE
Docker-compose with PostgreSQL

### ISSUE THREAD

**Issue by lorenzmeis** [WongSaang/chatgpt-ui#34]
Hi, the default docker-compose set-up is running fine, thank you for the great job! 
Now for permanent usage, I would like to use PostgreSQL instead of SQLite and I`m struggling at lot to make it work ;-) 
Could you describe the steps to configure your project to use postgres in a docker-compose scenario?

**Comment by lorenzmeis** [comment]
Hello, I added this in docker-compose and the db is deploying and starting fine
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD:=mypassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

**Comment by WongSaang** [comment]
Also, make sure that the container services are using the same network. 
For example, add the network parameter 
```
networks: 
  - chatgpt_ui_network
```
to your **db** service.

**Comment by lorenzmeis** [comment]
Hi, 
I need to start postgres without the network parameter in order to create the chatgpt database. If it`s created and I restart the BE, I`m getting connection error in BE: (environment: DB_URL=postgres://postgres:mypassword@localhost:5432/chatgpt)
File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
        
If I start DB with 
networks: 
  - chatgpt_ui_network
then I can`t connect to adminer to create the chatgpt DB

**Comment by WongSaang** [comment]
Please refer： https://github.com/WongSaang/chatgpt-ui/issues/27#issuecomment-1464924770

**Comment by lorenzmeis** [comment]
Perfect, now it works! 
I used: environment: DB_URL=postgres://postgres:mypassword@192.168.75.1:5432/chatgpt
and: 
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=chatgpt
    ports:
      - 5432:5432

**Comment by lorenzmeis** [comment]
I have a configuration working without using the host machine's internal IP address following the docker compose networking documentation https://docs.docker.com/compose/networking/. 
1.) environment: - DB_URL=postgres://postgres:mypassword@db:5432/chatgpt
2.) Docker compose:  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=chatgpt
    ports:
      - 5432:5432
    networks: 
      - chatgpt_ui_network

**Comment by WongSaang** [comment]
👍
