### ISSUE TITLE
The chat response will be aborted with "Server closed the connection unexpectedly"

### ISSUE THREAD

**Issue by hamada-yusuke** [WongSaang/chatgpt-ui#36]
Hello @WongSaang ,

I think it's a very good application.
The chat response will be aborted with the following error if it takes longer than 30 seconds:

> Failed to send message. Server closed the connection unexpectedly.

Checking the developer tool, the location where the error occurs is as follows:

https://github.com/WongSaang/chatgpt-ui/blob/878fda0054b525d89e63ada06469c31e7a3349f5/pages/index.vue#L78

I think it is caught in a timeout somewhere(nginx? or gunicorn?), is it possible to fix it?

**Comment by WongSaang** [comment]
Thank you for the feedback.

I have also encountered this issue and will fix it as soon as possible.

**Comment by WongSaang** [comment]
Hello, 

After investigation, it was found that the default timeout of gunicorn was too short, which caused this issue. 

The timeout of gunicorn workers has been updated from the default 30 seconds to 60 seconds. I believe that this can greatly reduce the probability of this error occurring. 

Please pull the latest backend image. 

Your feedback is very helpful, thank you!

**Comment by spencerwongfeilong** [comment]
I have confirmed 60s is not enough for a 1000 words response. With chatgpt 4 going to 8192 token, it is recommended to set this to 300s. But I think it can go higher. 

For your information, I tried other similar chatgpt client on github and experienced the same problem. However adjusting the time out to 600s solve the issue for long response.

**Comment by WongSaang** [comment]
> I have confirmed 60s is not enough for a 1000 words response. With chatgpt 4 going to 8192 token, it is recommended to set this to 300s. But I think it can go higher.
> 
> For your information, I tried other similar chatgpt client on github and experienced the same problem. However adjusting the time out to 600s solve the issue for long response.

Hello,

The latest version of the WSGI server has set the default timeout to 180 seconds. If it is not enough, you can modify the environment variable `WORKER_TIMEOUT`, for example,

```
  backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - WORKER_TIMEOUT=300
```

**Comment by WongSaang** [comment]
@spencerwongfeilong  https://github.com/WongSaang/chatgpt-ui-server/releases/tag/v2.4.0
