### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by playhousehosting** [WongSaang/chatgpt-ui#37]
Hello, 

I am enjoying this project. Thank you for all of your hard work. I was wondering if it would be possible to add some of the features from this project (https://github.com/qunash/chatgpt-advanced) to your project.  

Thanks in advance,

**Comment by WongSaang** [comment]
Thank you for your feedback. Could you be more specific about which features of the project you appreciate or desire?

**Comment by WongSaang** [comment]
Hello.

This feature has been implemented, please deploy the latest image and check the latest updates section in the readme.

**Comment by playhousehosting** [comment]
Thank you so much, and thank you for all of your hard work on this project!
