### ISSUE TITLE
admin 403

### ISSUE THREAD

**Issue by sedatabase** [WongSaang/chatgpt-ui#38]
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

**Comment by vudinhhung88** [comment]
I think you are using wrong domain. Make sure you use same domain as you input when start docker

**Comment by sedatabase** [comment]
> Yanlış alan adı kullandığınızı düşünüyorum. Docker'ı başlatırken girdiğiniz etki alanıyla aynı etki alanını kullandığınızdan emin olun

I set it up as localhost when I set it up, I'm trying to run it directly on the ip address, it's a vps server.

**Comment by sedatabase** [comment]
> I think you are using wrong domain. Make sure you use same domain as you input when start docker

I set it up as localhost when I set it up, I'm trying to run it directly on the ip address, it's a vps server.

**Comment by vudinhhung88** [comment]
What did you input to domain field when start the docker image?

**Comment by sedatabase** [comment]
I wrote the ip address of the VPS server and made it "up" by editing the required fields from the yaml file.

**Comment by WongSaang** [comment]
Please refer to this:  https://github.com/WongSaang/chatgpt-ui/issues/15#issuecomment-1455951490
