### ISSUE TITLE
Something went wrong when registering

### ISSUE THREAD

**Issue by spencerwongfeilong** [WongSaang/chatgpt-ui#39]
Hello

I get the message "something went wrong" whenever making a new account.
I think it's a bug.

Althought "something went wrong", the account gets created and able to login.

Let me know what other information you need to help resolve the problem

**Comment by WongSaang** [comment]
Hello, 

Thank you for the feedback!

Could you provide some log information? You can set the environment variable `DEBUG=True` in the **wsgi-server** to display backend errors.

**Comment by spencerwongfeilong** [comment]
Hello 

this is the error

CommandError: Error: That username is already taken.
[2023-03-19 14:07:20 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-19 14:07:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2023-03-19 14:07:20 +0000] [1] [INFO] Using worker: sync
[2023-03-19 14:07:20 +0000] [10] [INFO] Booting worker with pid: 10
Unauthorized: /api/account/user/
172.29.128.3 - - [19/Mar/2023:14:07:26 +0000] "GET /api/account/user/ HTTP/1.0" 401 58 "https://XXX.yyy.ZZZ/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
[2023-03-19 14:08:22 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
[2023-03-19 14:08:22 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-19 14:08:23 +0000] [11] [INFO] Booting worker with pid: 11
172.29.128.3 - - [19/Mar/2023:14:08:23 +0000] "GET /admin/auth/user/ HTTP/1.0" 200 16917 "https://AAA.yyy.ZZZ/admin/chat/setting/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.29.128.3 - - [19/Mar/2023:14:08:23 +0000] "GET /admin/auth/user/ HTTP/1.0" 200 16917 "https://AAA.yyy.ZZZ/admin/chat/setting/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.29.128.3 - - [19/Mar/2023:14:08:23 +0000] "GET /admin/jsi18n/ HTTP/1.0" 200 3343 "https://AAA.yyy.ZZZ/admin/auth/user/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Bad Request: /api/account/registration/

28.3 - - [19/Mar/2023:14:09:11 +0000] "POST /api/account/registration/ HTTP/1.0" 400 68 "https://XXX.yyy.ZZZ/account/signup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
[2023-03-19 14:09:56 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:11)
[2023-03-19 14:09:56 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-19 14:09:56 +0000] [12] [INFO] Booting worker with pid: 12
172.29.128.3 - - [19/Mar/2023:14:10:15 +0000] "GET /admin/auth/user/ HTTP/1.0" 200 17325 "https://AAA.yyy.ZZZ/admin/chat/setting/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.29.128.3 - - [19/Mar/2023:14:10:15 +0000] "GET /admin/jsi18n/ HTTP/1.0" 200 3343 "https://AAA.yyy.ZZZ/admin/auth/user/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.29.128.3 - - [19/Mar/2023:14:10:17 +0000] "GET /admin/auth/user/ HTTP/1.0" 200 17325 "https://AAA.yyy.ZZZ/admin/chat/setting/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.29.128.3 - - [19/Mar/2023:14:10:17 +0000] "GET /admin/jsi18n/ HTTP/1.0" 200 3343 "https://AAA.yyy.ZZZ/admin/auth/user/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

**Comment by WongSaang** [comment]
![image](https://user-images.githubusercontent.com/46235412/226229577-3c61a350-7ae7-4ce1-baa9-5cc78a9ff936.png)

Hello, it seems like I have found a lead. However, due to the error message being scrambled, I cannot confirm the cause yet. Could you please provide the form information you filled out during registration so that I can replicate this issue? Sensitive information can be ignored.

**Comment by spencerwongfeilong** [comment]
I randomly filled up account information and it always happen. 

You can try this 
User name: hello
Email: hello@gmail.com
Pw: hellohello

**Comment by WongSaang** [comment]
Have you set up SMTP email server?

**Comment by spencerwongfeilong** [comment]
I did both cases. 

Set up smtp, issue occurs. 
Disable smptp, issue still occur.

**Comment by WongSaang** [comment]
Can you provide configuration of your `wsgi-server`?

**Comment by spencerwongfeilong** [comment]
here u go

```
  backend-wsgi-server:
    container_name: chatgpt-ui-wsgi-server
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - APP_DOMAIN=xxx.yyy.zzz
      #- OPENAI_API_PROXY=https://openai.proxy.com/v1 # Proxy for https://api.openai.com/v1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      # - CSRF_COOKIE_SECURE=False
      # - CSRF_COOKIE_SAMESITE=None
      # If you want to use the email verification function, you need to configure the following parameters
      #- EMAIL_HOST=redacted
      #- EMAIL_PORT=redacted
      #- EMAIL_HOST_USER=redacted
      #- EMAIL_HOST_PASSWORD=redacted
      #- EMAIL_USE_TLS=True
      #- DEBUG=True
    volumes:
      - /share/Container/chatgpt/db/db.sqlite3:/app/db.sqlite3
    ports:
      - '8880:8000'      
```

**Comment by WongSaang** [comment]
Hello, thank you for the feedback. 
It seems there is indeed a bug with the email configuration. Could you please try adding the following environment variable to the **wsgi-server** and see if it works?
```
  backend-wsgi-server:
    container_name: chatgpt-ui-wsgi-server
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
        - ...
        - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
        - ...
```

**Comment by spencerwongfeilong** [comment]
test and did not get an error anymore! thank you

**Comment by spencerwongfeilong** [comment]
btw do u have a donation link?

**Comment by WongSaang** [comment]
> test and did not get an error anymore! thank you

This environment variable outputs the registration activation email to the console. If it works, it may indicate that your previously configured SMTP service cannot send emails. I suggest testing with another SMTP client. If you do not need the activation email feature, you can keep this environment variable.

**Comment by spencerwongfeilong** [comment]
You are saying that I should keep the environment variable with smtp configuration?

**Comment by spencerwongfeilong** [comment]
In the event if I do not wish for email verification, do I still keep the environment variable?

**Comment by spencerwongfeilong** [comment]
Hello. 

Here's an update. If I were to enable a smtp email client, it does not send the email address to the newly registered user. 

Similarly if I disable smtp email client, it shows a prompt that verification email has been sent to the newly registered user. 

Thank you.

**Comment by WongSaang** [comment]
> If you do not need the activation email feature, you can keep this environment variable.

Sorry, I didn't express clearly. 

If you don't need the function of sending activation emails, please keep this environment variable `EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend`
If you need to send activation emails, please remove this environment variable and make sure the SMTP configuration is correct.
You can use a third-party SMTP client to test whether the same configuration can send emails normally.

**Comment by spencerwongfeilong** [comment]
Hello 

thank you for the clarification.

if i include the environment variable and register for a new user, the webpage will display the following

"Verify your email
We've sent a verification email to XXXXXXXXXXXXXX@gmail.com.
Please check your inbox and click the link to verify your email address."

it is possible to change this message to perhaps "Your registration is successful. Please proceed to login to your account.", since activation emails are not sent.

**Comment by WongSaang** [comment]
Thank you for your suggestion, I will optimize this feature as soon as possible.

**Comment by admin-xpc** [comment]
> 您好，这个问题已经在新版本中解决了。请拉取最新的镜像。
> 
> 现在后台增加了一个环境变量**ACCOUNT_EMAIL_VERIFICATION来控制邮箱验证方式，当你将****ACCOUNT_EMAIL_VERIFICATION**的值设置为时`none`，用户注册完成后会提示直接登录。
> 
> <img alt="图像" width="838" src="https://user-images.githubusercontent.com/46235412/226372988-cbeb5511-473d-4fdf-86dc-6dc4518e679d.png">
您发表后我第一时间删除原镜像并且拉取了新的镜像并进行了修改，还是不行
<img width="692" alt="image" src="https://user-images.githubusercontent.com/59109756/226379798-04943905-2163-4b8d-9ddc-8c640f3911c1.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/59109756/226379891-839b7c51-7ac9-4c3b-8ed4-0aeda63d4b17.png">

**Comment by WongSaang** [comment]
> 这样可以吗？ ![470F87F3-5A18-4C4A-94BE-41D7BD2503D7](https://user-images.githubusercontent.com/59109756/226389544-86d4c922-dd6a-41ce-aca6-13984ed755d3.png) ![06070DB1-F9D4-4422-953F-2E0D211B4BD6](https://user-images.githubusercontent.com/59109756/226389636-d913c848-7f8d-4851-b09d-3b3fa1f782e5.png) ![2D148C1B-BBA3-467F-9638-007C9E2C6752](https://user-images.githubusercontent.com/59109756/226389709-33990851-9331-4263-88b3-d2e945f628d0.png)

这应该是配置问题，但现在看不出来具体原因。可以在 wsgi-server 添加环境变量 DEBUG=True, 然后提供容器内日志吗？

**Comment by admin-xpc** [comment]
> 容器
新手不太会。。。我应该把这个debug添加到哪个位置，然后怎么运行容器日志。:(

**Comment by admin-xpc** [comment]
> > > 容器
> > > 新手不会太会。。。我应该把这个调试添加到哪个位置，然后怎么运行容器日志。:(
> 
> 你是通过命命令行署的吗？

我是通过shell 一键弄得

**Comment by WongSaang** [comment]
> > > > 容器
> > > > 新手不会太会。。。我应该把这个调试添加到哪个位置，然后怎么运行容器日志。:(
> > 
> > 
> > 你是通过命命令行署的吗？
> 
> 我是通过shell 一键弄得

好的，我看看能不能复现你的问题。另外，你也可以先使用 admin 直接登录。在可以聊天之前，先去后台配置 api key

**Comment by admin-xpc** [comment]
> > > > > 容器
> > > > > 新手不会太会。。。我应该把这个调试添加到哪个位置，然后怎么运行容器日志。:(
> > > 
> > > 
> > > 你是通过命命命令行踪的吗？
> > 
> > 
> > 我是通过shell一键搞得
> 
> 好的，我看不能复现你的问题。另外，你也可以先使用admin直接登录。在可以聊天之前，先去后台配置api key

好的，麻烦您了，十分感谢

**Comment by admin-xpc** [comment]
> > > > > > 容器
> > > > > > 新手不会太会。。。我应该把这个调试添加到哪个位置，然后怎么运行容器日志。:(
> > > > 
> > > > 
> > > > 你是通过命命命令走路的吗？
> > > 
> > > 
> > > 我是通过shell一键搞得
> > 
> > 
> > 好的，我看不能复现你的问题。另外，你也可以先使用admin直接登录。在可以聊天之前，先去后台配置api key
> 
> 好的，麻烦您了，十分感谢

需要使用服务器的地址和root吗？我该怎么发给您

**Comment by WongSaang** [comment]
@admin-xpc 我已经复现了这个问题，并更新了 docker-compose.yml 文件。

请登录你的服务器再次执行命令：
```
bash <(curl -Ls https://raw.githubusercontent.com/WongSaang/chatgpt-ui/main/deployment.sh)
```

现在默认是关闭邮箱验证的，如果你想打开注册邮箱验证，命令执行成功后，在当前目录下有一个 docker-compose.yml 文件，可以修改里边的环境变量来配置邮箱服务，但这需要一些 docker 知识。

**Comment by admin-xpc** [comment]
> @admin-xpc我已经发现了这个问题，并更新了 docker-compose.yml 文件。
> 
> 请登录你的服务器再次执行命令：
> 
> ```
> bash <(curl -Ls https://raw.githubusercontent.com/WongSaang/chatgpt-ui/main/deployment.sh)
> ```
> 
> 现在默认验证的，如果如果打开注册注册邮箱知道。

可以了，谢谢您！

**Comment by WongSaang** [comment]
好的，那我关闭这个 issue 了，如有问题再另开一个。
