### ISSUE TITLE
Add password authentication

### ISSUE THREAD

**Issue by suixhxy** [WongSaang/chatgpt-ui#4]

**Comment by WongSaang** [comment]
I was going to add a user module.
But your requirement is just basic authentication, why not just use nginx as a proxy 🤭

**Comment by suixhxy** [comment]
Thank you very much
Thanks, I figured out that I could deploy an nginx proxy myself and configure a basic password authentication.
By the way, what is the function of the user module you mentioned? Can I talk about it?

**Comment by WongSaang** [comment]
It might be possible to add a configuration that supports external database connections to manage users. 
Do you have any good ideas? 🙂

**Comment by suixhxy** [comment]
I have an idea, and it goes like this:
The OpenAI Api Key is configured as a hidden configuration.
The front end uses user login mode,
Manage users. You can create and delete users.
Only authorized users can access:
http://192.168.1.196:9090/.
After login, common users cannot modify the OpenAI Api Key configuration.
Only administrators can configure OpenAI Api keys.
If you don't want a user to have access, you can revoke his permissions.
In this way, security is increased. It is more convenient to manage users and facilitate team cooperation.

**Comment by WongSaang** [comment]
Hello, version 2 now supports user authentication.

**Comment by TuXbOy06** [comment]
Hi,
I want to try your project but it is asking me for a login and password ! 
Can you help ?

**Comment by TuXbOy06** [comment]
Thanks but it doesn't work
![image](https://user-images.githubusercontent.com/13116073/221850325-feb6a6d8-a9d3-4834-a5b6-09fee50abd59.png)
![image](https://user-images.githubusercontent.com/13116073/221850411-79fc7cfb-d192-40da-bb8b-9e4d6598cc71.png)

**Comment by WongSaang** [comment]
Sorry, the previous version might have contained some bugs which I have now fixed. If you are still interested, you can run “docker compose” again following the example in the README file to pull the latest image. 
If you have any further issues, I look forward to hearing from you again. Thank you!

**Comment by TuXbOy06** [comment]
Nice it is working now thanks for your help

**Comment by WongSaang** [comment]
😁 I made another update just a few minutes ago.

I have updated the image and also the docker-compose configuration example in Readme .

You can copy the docker-compose configuration again and pull the latest image by running the command `docker-compose up --pull always`.
