### ISSUE TITLE
feature request: mobile device UI adaptation

### ISSUE THREAD

**Issue by oiabtt** [WongSaang/chatgpt-ui#43]
Hi, thanks for your project. 

feature request: When I open the page on a mobile device, the website still displays the desktop layout instead of the mobile layout, which makes it difficult to use this project on mobile devices. Could you fix this?

BUG: In addition, there is currently a bug in the project where there is no back button when the user clicks the “language” button.The user is stuck on the language page and cannot exit.

**Comment by WongSaang** [comment]
> feature request: When I open the page on a mobile device, the website still displays the desktop layout instead of the mobile layout, which makes it difficult to use this project on mobile devices. Could you fix this?

Can you please provide a screenshot if it's convenient for you? In addition, have you selected the "desktop version" option in your mobile browser?

**Comment by WongSaang** [comment]
> BUG: In addition, there is currently a bug in the project where there is no back button when the user clicks the “language” button.The user is stuck on the language page and cannot exit.

This is indeed a bug. Thank you for reporting it!

**Comment by oiabtt** [comment]
> 

After testing, there are no issues with the mobile adaptation of this project. The problem lies with the URL forwarding

**Comment by WongSaang** [comment]
Okay, then I will close this issue.
