### ISSUE TITLE
有考虑支持GPT4吗?

### ISSUE THREAD

**Issue by zhkufish** [WongSaang/chatgpt-ui#44]
好像GPT4的接口跟GPT3的基本一致的,不知道要调整哪些东西呢.

**Comment by zimmra** [comment]
The API documentation states that the models `gpt-3.5-turbo` and `gpt-4` are effectively interchangable. 

>For many basic tasks, the difference between GPT-4 and GPT-3.5 models is not significant. However, in more complex reasoning situations, GPT-4 is much more capable than any of our previous models.

Because of the increased complexity, the token limit is raised to 8,192 for `gpt-4` (compared to 4,096 for `gpt-3.5-turbo`)

**Comment by zimmra** [comment]
> The API documentation states that the models `gpt-3.5-turbo` and `gpt-4` are effectively interchangable.

@WongSaang One thing I have discovered as a difference is the ability to web query. 

gpt-3.5-turbo has no issue interpreting the search results with your 'Web Search' option toggle and using in its response

gpt-4 replies: 
>I'm sorry, but I cannot provide web search results or perform a search for you. However, I can help answer any questions or provide information based on what you ask. Please provide a query or topic you'd like to know more about, and I'll do my best to assist you.

**Comment by WongSaang** [comment]
Now supporting GPT-4.

https://github.com/WongSaang/chatgpt-ui#updates
