### ISSUE TITLE
Failed to send message. HTTP 500 -

### ISSUE THREAD

**Issue by spencerwongfeilong** [WongSaang/chatgpt-ui#46]
I realised the issue.

cloudflare tunnel is blocking the connection. not sure why. sorry i re-open the issue.

**Comment by WongSaang** [comment]
Sorry, I haven't used Cloudflare Tunnel before. The message from GPT is sent through SSE ([Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)). You can check if Cloudflare Tunnel is blocking SSE or if there are any connection timeout restrictions.

**Comment by 0evers** [comment]
> Sorry, I haven't used Cloudflare Tunnel before. The message from GPT is sent through SSE ([Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)). You can check if Cloudflare Tunnel is blocking SSE or if there are any connection timeout restrictions.

 I have the same issue without Cloudflare

**Comment by WongSaang** [comment]
> > Sorry, I haven't used Cloudflare Tunnel before. The message from GPT is sent through SSE ([Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)). You can check if Cloudflare Tunnel is blocking SSE or if there are any connection timeout restrictions.
> 
> I receive the same error message without Cloudflare

Can you provide some logging information within the container

**Comment by 0evers** [comment]
> > > Sorry, I haven't used Cloudflare Tunnel before. The message from GPT is sent through SSE ([Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)). You can check if Cloudflare Tunnel is blocking SSE or if there are any connection timeout restrictions.
> 
> > 
> 
> > I receive the same error message without Cloudflare
> 
> 
> 
> Can you provide some logging information within the container

It works again. The API had partial failures at the time I tested it.

**Comment by WongSaang** [comment]
Sometimes it is caused by instability of OpenAI's servers

**Comment by spencerwongfeilong** [comment]
I realise if i were to perform the search in incognito mode, the error goes away. Is there a cache somewhere inside the docker instance preventing the query from being sent to openai server?

**Comment by WongSaang** [comment]
Do you mean the browser's incognito  mode? That shouldn't be a problem inside the container. If you encounter this problem again, please provide the browser's network request error message

**Comment by spencerwongfeilong** [comment]
![image](https://user-images.githubusercontent.com/127573355/226871613-71b3350d-042a-481f-b815-b9917ec119bc.png)

the above picture is from LAN. As you can see i have 11.29 seconds when loading the page. It was a white screen before the CHATGPT client appeared.
