### ISSUE TITLE
unable to delete messages in conversation

### ISSUE THREAD

**Issue by spencerwongfeilong** [WongSaang/chatgpt-ui#48]
When deleting a message within a conversation, CHATgpt will prompt "Delete Fail"

Let me know how can i assist to help

**Comment by WongSaang** [comment]
I have also noticed this issue and I will fix it as soon as possible.

**Comment by spencerwongfeilong** [comment]
There is a bug with 2.2.7 

While deleting the message works, returning to the conversation will show all messages deleted.

**Comment by WongSaang** [comment]
Hello, 
This issue has been fixed in the latest version. Please pull the latest image. 
Both the front-end and back-end images need to be pulled.

**Comment by WongSaang** [comment]
> There is a bug with 2.2.7
> 
> While deleting the message works, returning to the conversation will show all messages deleted.

Please update to v2.2.8

**Comment by spencerwongfeilong** [comment]
Fixed and thank you!
