### ISSUE TITLE
在拉取较长的回答时，经常掉连接，无法完成对话

### ISSUE THREAD

**Issue by tsingchou** [WongSaang/chatgpt-ui#51]
在拉取较长的回答时，经常掉连接，无法完成对话，显示Failed to send message. Server closed the connection unexpectedly.

**Comment by WongSaang** [comment]
你好，感谢反馈！
大概多长时间？是最新的镜像吗？

https://github.com/WongSaang/chatgpt-ui/issues/36#issuecomment-1475107771

**Comment by tsingchou** [comment]
30秒，就断开连接，镜像不是最新版，应该是2.1.9

**Comment by WongSaang** [comment]
之前更新过这个地方，提升到 60 秒了，可以拉下最新镜像

**Comment by GOvEy1nw** [comment]
Hi, I'm having this issue too, I have tweaked the code to allow the max tokens of 4096, will increasing the timeout further help? Or is there a better solution?

**Comment by spencerwongfeilong** [comment]
Should the time out of the workers be set to 120s?

Seems 60s is not enough.

**Comment by spencerwongfeilong** [comment]
When I ask chatgpt to summarise the history of a country in 1000 words. It will time out for sure.

**Comment by spencerwongfeilong** [comment]
See here

https://github.com/WongSaang/chatgpt-ui/issues/36#issuecomment-1501115575

**Comment by WongSaang** [comment]
Similar to https://github.com/WongSaang/chatgpt-ui/issues/36
