### ISSUE TITLE
instances where the django administration will lag so much that loading will give a white screen.

### ISSUE THREAD

**Issue by spencerwongfeilong** [WongSaang/chatgpt-ui#52]
Hello

There are instances where by the django adminstration dashboard and the CHATGPT UI will lag, giving a white screen. I created less than 20 users. 

May i know how can i help you with the issue?

Thank you

**Comment by WongSaang** [comment]
Can you provide some screenshots of the browser's network requests？

**Comment by spencerwongfeilong** [comment]
hello thank u for the response. i will try again when i encounter the issue

**Comment by spencerwongfeilong** [comment]
I have posted screen shots here. 

https://github.com/WongSaang/chatgpt-ui/issues/46

Also I migrated my docker container to another machine. I will monitor whether the issue happen again or not.

**Comment by spencerwongfeilong** [comment]
Hello 

I have Setup cloudflare tunnel as part of the stack. I don't seem to have http 500 error any more. Thank you.
