### ISSUE TITLE
Lose database when updating containers

### ISSUE THREAD

**Issue by GOvEy1nw** [WongSaang/chatgpt-ui#53]
When I update the containers via docker-compose, my whole database gets lost, including API key and users. Is there a way to avoid that? Also, even if I re-add the same user/password again, I struggle to log into the client in the same browser, but it works in a different browser, which I assume is a cache issue, but I don't understand why it wouldn't work if its the same user/pass?

**Comment by GOvEy1nw** [comment]
I realise that this is due to not setting a separate database link now. How would I adapt the docker-compose to also install a suitable database container and link it all up?

**Comment by WongSaang** [comment]
![image](https://user-images.githubusercontent.com/46235412/226795061-e34747e1-b0b9-4bab-8f8f-6519efa0a2fe.png)

Can you tell me how you configured the database connection?

**Comment by WongSaang** [comment]
You can refer this issue: https://github.com/WongSaang/chatgpt-ui/issues/29
