### ISSUE TITLE
Real-time streaming of response / general speed improvements

### ISSUE THREAD

**Issue by GOvEy1nw** [WongSaang/chatgpt-ui#58]
I'm not sure why, but response from the bot feels quite slow. I'm not sure if its due to a deeper issue, or if it's because it's not 'streaming' the response, and just loading it in chunks instead.

It'd be great if you could add real-time streaming of the response. I think psychologically it makes the response feel quicker.

I also seem to get slower responses when I set max tokens higher (even if the response is short), and if I set max tokens at a certain level I end up just getting error 500 messages for some reason. This often happens when above 1200 tokens, but the model supports 4096 max tokens, so I'm not sure why that is.

**Comment by WongSaang** [comment]
Hello.

I can tell you explicitly that the interface of the conversation is responding in real time to the chatgpt stream information.

Not knowing where your server is deployed, this problem is mostly caused by the network. So, I suggest you to solve this problem from the server node and network.

**Comment by GOvEy1nw** [comment]
Hi @WongSaang I've finally figured out what was wrong!

All very simple really, I was getting the error `Failed to send message. Server closed the connection unexpectedly.`, because the amount of tokens used for the prompt and the max completion tokens exceeded the total tokens.

Related error from the log:

`2023-03-26 19:52:33 openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 5128 tokens (1032 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.`

It would be great if the error message could be clearer that the token limit is exceeded, to avoid confusion.

The reason I was confused by this is because I thought 'Max Tokens' controlled the overall max tokens, but I've discovered it only controls the max response/completion tokens, so when I was setting it to the max of 4096, the call for completion was eating up all the tokens and not leaving any for the prompt itself.

Naturally, I've managed to solve this by setting max tokens to a lower value of 3096 (the above was just an extreme example).

In my quest to figure out what was happening, I found these token limits in the 'views.py' in the server repository below:

```
def get_current_model():
    model = {
        'name': 'gpt-3.5-turbo',
        'max_tokens': 4096,
        'max_prompt_tokens': 3096,
        'max_response_tokens': 1000
    }
```

From playing with those limits, I'm not sure if they are taken into account or not, but it would be great if we could set the max prompt tokens as well as the current max response tokens slider, and if possible, show a warning if the prompt we're typing would exceed the token limit. 

Ideally, it would also be great if instead of the 'max tokens' setting in the front end, there was a way of setting a ratio instead? Eg, 2 sliders, one for prompt tokens, one for response tokens. If you slide the prompt token slider up, it automatically slides the response tokens slider down and vice-versa, always keeping the total tokens at the maximum of 4096 (or whatever max is set in the back-end). That way users can flexibly squeeze longer responses if needed, or give longer prompts if needed.

**Comment by WongSaang** [comment]
> Thank you @WongSaang I've noticed you've implemented the error message!
> 
> As an expansion on the user controlled token slider, I wonder if you could also add a hint of how many words the amount of tokens roughly equal (~750 words per 1000 tokens for 3.5Turbo), to make it easier for the general user to understand.
> 
> So, for example, it could be a single slider that the user can slide between giving the prompt or the response more tokens to use. If the slider is in the centre, it would give 2048 tokens to the prompt and 2048 tokens to the response. If you slide the slider to the left the prompt gets more tokens, if you slide it to the right the response gets more tokens.
> 
> visual example:
> 
> <img alt="image" width="763" src="https://user-images.githubusercontent.com/45126527/228059981-e2d84dd0-9e1c-44d2-90b2-96edc82e32a2.png">
> 
> <img alt="image" width="763" src="https://user-images.githubusercontent.com/45126527/228060492-8c71ae77-a76e-487c-9df8-370b7793e0eb.png">

Good suggestion, but the suggestion is not related to the topic of this issue, could you please create a new issue ?
