### ISSUE TITLE
NUXT_PUBLIC_* env variables not processed

### ISSUE THREAD

**Issue by zimmra** [WongSaang/chatgpt-ui#59]
The following env variables are not processed by the docker container

- `NUXT_PUBLIC_APP_NAME`
- `NUXT_PUBLIC_TYPEWRITER`
- `NUXT_PUBLIC_TYPEWRITER_DELAY`

I _believe_ this is because of `nuxt generate` occuring at the docker-image build time, preventing nuxt from processing additional environment variables due to the app already being built

**Comment by zimmra** [comment]
Confirmed/replicated issue by forking container and manually setting up `runtimeConfig` in `nuxt.config.ts`, then rebuilding the docker image

I was able to change the `appName` `typewriter` and `typewriterDelay` options manually and they were reflecting in the webapps GUI

**Comment by WongSaang** [comment]
Hello,

Thanks for the feedback!

Yes, `appName` was not read from environment variables before, I will improve this part as soon as possible.

**Comment by WongSaang** [comment]
Hello, the latest version has fixed this problem
