### ISSUE TITLE
/usr/bin/docker-current: manifest for docker.io/wongsaang/chatgpt-ui:latest not found. See '/usr/bin/docker-current run --help'

### ISSUE THREAD

**Issue by 2682856025** [WongSaang/chatgpt-ui#6]
/usr/bin/docker-current: manifest for docker.io/wongsaang/chatgpt-ui:latest not found.
See '/usr/bin/docker-current run --help'

**Comment by WongSaang** [comment]
I'm sorry, I'm unable to reproduce your issue. May I know what version of Docker you are using?
