### ISSUE TITLE
-

### ISSUE THREAD

**Issue by oiabtt** [WongSaang/chatgpt-ui#60]

**Comment by WongSaang** [comment]
Hello,

Thanks for the feedback. 

Just set the value of environment variable **APP_DOMAIN** to `yourdomain:9000`

![image](https://user-images.githubusercontent.com/46235412/227109959-67dfb8ca-c9e0-4fc0-87c8-7d0cffa20350.png)

**Comment by oiabtt** [comment]
> Hello,
> 
> Thanks for the feedback.
> 
> Just set the value of environment variable **APP_DOMAIN** to `yourdomain:9000`
> 
> ![image](https://user-images.githubusercontent.com/46235412/227109959-67dfb8ca-c9e0-4fc0-87c8-7d0cffa20350.png)

Thank, like the Nginx configuration shown above
chat page:  chat.example.com
admin page: manager.example.com
There are two domains in total, so which domain should I set to APP_DOMAIN in order to access the admin page without encountering 403 CSRF error?

I have tried set  chat.example.com to APP_DOMAIN, chat page is ok but admin page (manager.example.com) shows 403 CSRF.

**Comment by WongSaang** [comment]
try:  APP_DOMAIN="manager.example.com:9000"

**Comment by oiabtt** [comment]
> 

After set manager.example.com to APP_DOMAIN and modify Nginx config, error disappear, thanks.

**Comment by WongSaang** [comment]
Okay, then I will close this issue.
