### ISSUE TITLE
admin账户登陆时提示403错误：CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by duanyunlun** [WongSaang/chatgpt-ui#62]
我是用Docker在Openwrt系统中部署的，不知道是不是缺少了什么第三方库还是别的环境参数？

**Comment by WongSaang** [comment]
Suggest you read these issues first
https://github.com/WongSaang/chatgpt-ui/issues?q=is%3Aissue+CSRF

**Comment by duanyunlun** [comment]
谢谢，已解决
