### ISSUE TITLE
Web Search Error (Or Improper Syntax)

### ISSUE THREAD

**Issue by zimmra** [WongSaang/chatgpt-ui#65]
Is there a syntax needed to use the web search functionality? I entered a question and this was the reply:

>It seems that you have not provided any query or web search results to respond to. Please provide the necessary information, and I will do my best to provide a comprehensive reply to your query using the provided web search results.

**Comment by WongSaang** [comment]
The web search feature is currently based on duckduckgo. After a user sends
a question, the back-end application first searches for results in
duckduckgo and then provides them to ChatGTP.

This may be a bug in the backend application, I will check it.

**Comment by WongSaang** [comment]
Fixed: https://github.com/WongSaang/chatgpt-ui/commit/323f10844bcdd69177802e19bee3f310794cf6b6
