### ISSUE TITLE
docker-compose up localhost:9000

### ISSUE THREAD

**Issue by yangxuesong** [WongSaang/chatgpt-ui#66]

**Comment by yangxuesong** [comment]
Forbidden (403)
CSRF verification failed. Request aborted.

**Comment by admin-xpc** [comment]
我也遇到了同样的问题
<img width="355" alt="image" src="https://user-images.githubusercontent.com/59109756/227425662-4b4a81e7-a5ec-4407-add3-48e2912fbb96.png">

**Comment by WongSaang** [comment]
You can take a look at these issues first to see if you can solve the problem.
https://github.com/WongSaang/chatgpt-ui/issues?q=is%3Aissue+CSRF
