### ISSUE TITLE
bind 0.0.0.0:80 failed

### ISSUE THREAD

**Issue by yangxuesong** [WongSaang/chatgpt-ui#67]
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/03/24 11:17:57 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)

using podman version: podman version 3.2.3
podman-composer version  0.1.7dev
podman --version
podman version 3.2.3

**Comment by WongSaang** [comment]
It seems that your port 80 is being used by another service.
