### ISSUE TITLE
关于https

### ISSUE THREAD

**Issue by admin-xpc** [WongSaang/chatgpt-ui#69]
您好，我实在找不到解决办法才来麻烦您一下；
是这样的，我拉取您的项目并且成功解决了问题后，我又下载了宝塔客户端对域名进行ssl证书配置，配置完毕后发现并不行，我该怎么办:(

**Comment by WongSaang** [comment]
告诉我你怎么配的

**Comment by WongSaang** [comment]
图片没显示

**Comment by admin-xpc** [comment]
![image](https://user-images.githubusercontent.com/59109756/227523189-575d5f19-45e8-4328-8ddf-d6acbffc9717.png)
给您添麻烦了

**Comment by WongSaang** [comment]
我看你的域名是可以访问，就是证书可能还不正常。
你说的不行是指什么不行？

Mray-FL ***@***.***> 于 2023年3月24日周五 20:37写道：

**Comment by admin-xpc** [comment]
那我要怎么装一个正常的证书呢，麻烦您指点一下.....

**Comment by WongSaang** [comment]
你是用 let's encrypt 吗？可以点开网站设置的 SSL 界面截个图吗？

Mray-FL ***@***.***> 于 2023年3月24日周五 20:42写道：

**Comment by admin-xpc** [comment]
![image](https://user-images.githubusercontent.com/59109756/227526901-4f3397ab-fdda-47fa-b6c2-61cce84d9aaa.png)
我的let's失败了，我就上传的其他的证书

**Comment by WongSaang** [comment]
是不是配置了反向代理？先把反向代理，强制HTTPS关掉，再重新申请 let's encrypt

**Comment by admin-xpc** [comment]
![image](https://user-images.githubusercontent.com/59109756/227532744-db84ff81-2adc-4521-a2c8-bf3f08397959.png)
我重新申请了let's encrypt 成功后我开启了反向代理，还是不行。。。https://gpt.xpcyy.com还是打不开

**Comment by WongSaang** [comment]
不开反向代理能请求到页面吗？
看看你的反向代理配置

Mray-FL ***@***.***> 于 2023年3月24日周五 21:24写道：

**Comment by admin-xpc** [comment]
开关与否都无法进入，我用cf打开代理的话，发消息就发不出去，难搞哦:(

**Comment by WongSaang** [comment]
用 CF 做解析吗？墙内网络你懂的，修改C F的dns要等很久才刷新。

建议先解析个新的子域名，CF 别开proxy。在宝塔申请证书，再试下。

Mray-FL ***@***.***> 于 2023年3月24日周五 21:32写道：

**Comment by ilovefreesw** [comment]
I am using Cloudflare and can't seem to have HTTPS enabled with or without proxied record.

**Comment by WongSaang** [comment]
> I am using Cloudflare and can't seem to have HTTPS enabled with or without proxied record.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/46235412/229289149-97d849da-5ff2-47ab-93d0-59e1644abeeb.png">

**Comment by WongSaang** [comment]
> I am using Cloudflare and can't seem to have HTTPS enabled with or without proxied record.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/46235412/229289278-491f6497-f409-4cb4-9f5c-c5dde9140f23.png">

**Comment by ilovefreesw** [comment]
@WongSaang With proxied record it doesn't work. For me it works with Flexible SSL mode and DNS Only A record.
