### ISSUE TITLE
web page layout is messy when using custom font in browser

### ISSUE THREAD

**Issue by tsiank** [WongSaang/chatgpt-ui#71]
web page layout is messy when using custom font in browser.
https://i.328888.xyz/2023/03/24/i4UcOP.jpeg

**Comment by WongSaang** [comment]
It seems that the icon font file has not been loaded. Have you changed the icon font?

**Comment by tsiank** [comment]
I find the cause. it is caused by using the chrome extension https://chrome.google.com/webstore/detail/force-custom-fonts/hckjchjpkmbihoocajjpjajkggbccgee , deactivate this extension, this page layout is normal now.

**Comment by WongSaang** [comment]
Okay
