### ISSUE TITLE
How can I use an API with my own domain name and where can I make modifications?

### ISSUE THREAD

**Issue by chenweilie** [WongSaang/chatgpt-ui#72]
After adding an API KEY, it's not working and I suspect there might be an access issue. I want to try using my own API instead.

**Comment by WongSaang** [comment]
https://github.com/WongSaang/chatgpt-ui/issues/74#issuecomment-1483763949

**Comment by WongSaang** [comment]
![image](https://user-images.githubusercontent.com/46235412/227707094-22da11c3-9ac6-4082-91d7-7d8215792a0d.png)

**Comment by spencerwongfeilong** [comment]
hello

may i know https://openai.proxy.com/v1 -> this is referring to the wsgi server?

does it mean https://openai.proxy.com/v1 points to http://10.10.10.10:8000/v1 ?

**Comment by WongSaang** [comment]
No, in some places, their network cannot directly request the OpenAI API address, and they may need to deploy their own proxy server.
