### ISSUE TITLE
why using django admin to set openai api key instead of .env

### ISSUE THREAD

**Issue by handhikadj** [WongSaang/chatgpt-ui#75]
using .env will be much more easier to set. We've had the CSRF issues on django admin JUST to set the OpenAI API Key which should be fairly simple to do. using django admin just complicate stuff IMO

**Comment by WongSaang** [comment]
The original intent of this project was to support multiple users and data persistence, and the purpose of the admin panel is more than simply setting variables.

If you just want to use a simple client, I'm sure there are many alternatives.
