### ISSUE TITLE
TypeWriter not working

### ISSUE THREAD

**Issue by NandhaKishorM** [WongSaang/chatgpt-ui#76]
The streaming feature not working in the docker. 
  - NUXT_PUBLIC_APP_NAME='ChatGPT UI'
      - NUXT_PUBLIC_TYPEWRITER=true
      - NUXT_PUBLIC_TYPEWRITER_DELAY=100 has no impact on the UI even if we change it in compose file

**Comment by WongSaang** [comment]
Hello, Thank you for the feedback.

I also noticed that this environment variable is not available in
production. I will fix this issue as soon as possible.
The environment variable is available in build stage, and you can also
build your own version.

Nandakishor ***@***.***> 于 2023年3月25日周六 20:29写道：

**Comment by NandhaKishorM** [comment]
can you elaborate how I can build my own version?

**Comment by cb360** [comment]
修改此项目源码根目录下: nuxt.config.ts 文件：
将 typewriter: false改为true。
重新构建：yarn run build
将生成的.output文件夹替换掉原来的。
TypeWriter 功能就正常了。

chatgpt translate to english：

Please modify the nuxt.config.ts file in the root directory of this project: 
Change typewriter: false to typewriter: true. 
Rebuild the project with yarn run build. Replace the original folder with the newly generated .output folder. 
The TypeWriter feature should work properly after these steps.
 
runtimeConfig: {
        public: {
            appName: appName,
            **typewriter: true,**
            typewriterDelay: 50,
            customApiKey: false
        }
    },

**Comment by WongSaang** [comment]
Hello, the latest version has fixed this issue.
