### ISSUE TITLE
前端访问 报错Not Found The requested resource was not found on this server. 

### ISSUE THREAD

**Issue by tradingeva** [WongSaang/chatgpt-ui#79]
我已经用(curl -Ls https://raw.githubusercontent.com/WongSaang/chatgpt-ui/main/deployment.sh) 脚本进行部署 可以正常打开admin后台 但我访问前端就会出现报错Not Found The requested resource was not found on this server. 
![image](https://user-images.githubusercontent.com/115392265/227791994-e51c9981-bb1e-4f65-9c03-d484ab5d4b90.png)

**Comment by tradingeva** [comment]
已经解决 但是后台是这样 
![image](https://user-images.githubusercontent.com/115392265/227799566-086624a4-bab3-4552-9606-cac3bf25bfc5.png)

**Comment by dawarazhar11** [comment]
> It has been resolved but the background is like this ![image](https://user-images.githubusercontent.com/115392265/227799566-086624a4-bab3-4552-9606-cac3bf25bfc5.png)

How did you resolve this?
