### ISSUE TITLE
How to set OpenAI key

### ISSUE THREAD

**Issue by Boris-code** [WongSaang/chatgpt-ui#8]
how to set openAI key?

**Comment by WongSaang** [comment]
If you are using the sample Docker Compose configuration, you can access the local port bound to the backend-web-server service at localhost:9000 to log in to the management panel. Configure settings in the management panel.

Default superadmin account: admin
Default password: password

### After logging in
In the Settings model, add a record with the name "openai_api_key" and the value as your API key.

**Comment by Boris-code** [comment]
thank you
