### ISSUE TITLE
Allow the response to keep 'typing' even if I switch to a different tab?

### ISSUE THREAD

**Issue by GOvEy1nw** [WongSaang/chatgpt-ui#80]
I've noticed that the response will stop typing if I switch tabs, but then continue typing when I return to the UI. Is it possible to set it so the response will continue typing regardless of whether the tab is in focus or not?

**Comment by WongSaang** [comment]
@GOvEy1nw Hello, this issue has been fixed now. Please deploy the latest image.

https://github.com/WongSaang/chatgpt-ui/releases/tag/v2.3.6

**Comment by GOvEy1nw** [comment]
Thank you @WongSaang !
