### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 (Unauthorized)报错

### ISSUE THREAD

**Issue by tradingeva** [WongSaang/chatgpt-ui#83]
可以正常访问前端和后台 但是添加了openai key之后发送消息控制台报错 Failed to load resource: the server responded with a status of 401 (Unauthorized)  
![image](https://user-images.githubusercontent.com/115392265/227843619-78fe8d50-d5b4-4be0-8e67-6cddf32de3df.png)

**Comment by tradingeva** [comment]
![image](https://user-images.githubusercontent.com/115392265/227985934-04ed37af-6d8b-4a49-b39d-8b2dee9f74ec.png)
![image](https://user-images.githubusercontent.com/115392265/227985998-a8a22c50-18db-4e30-bdf8-b13c84e67576.png)
还是无法使用呢

**Comment by WongSaang** [comment]
请问是否配置了代理服务接口 `OPENAI_API_PROXY`？ 如果没有配置，方便说下你是在墙内部署还是在墙外？

**Comment by tradingeva** [comment]
我是在墙外的服务器进行部署 但我在墙内进行使用 没有配置 OPENAI_API_PROXY

**Comment by WongSaang** [comment]
你的部署方式能说下么？
另外，你可以在wsgi-server加一个环境变量 `DEBUT=True`，这样就可以看到容器日志，好判断到底是哪里的问题。

**Comment by tradingeva** [comment]
我是直接使用readme中的一键部署脚本部署的

**Comment by WongSaang** [comment]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/46235412/228242340-ae43370c-c8c5-4a87-b34c-301953a15233.png">
我注意到，你的网络请求地址后面都多一个 `:1`
你能查找下这个原因么
