### ISSUE TITLE
ERROR: manifest for docker.io/wongsaang/chatgpt-ui-wsgi-server:latest not found

### ISSUE THREAD

**Issue by yangxuesong** [WongSaang/chatgpt-ui#85]
docker-compose up -d

ERROR: manifest for docker.io/wongsaang/chatgpt-ui-wsgi-server:latest not found

**Comment by GOvEy1nw** [comment]
have you edited the docker-compose file at all? Working fine on this end

    image: wongsaang/chatgpt-ui-wsgi-server:latest
