### ISSUE TITLE
Add headers for prompts

### ISSUE THREAD

**Issue by zyrakq** [WongSaang/chatgpt-ui#86]
Is it possible to add headers for prompts? It is very inconvenient to recognize prompts by its initial text. Especially when there are a lot of such prompts.

**Comment by erritis** [comment]
https://github.com/WongSaang/chatgpt-ui/pull/97

https://github.com/WongSaang/chatgpt-ui-server/pull/7

**Comment by WongSaang** [comment]
Already merged and released. **Thank you for your hard work, @erritis.**
