### ISSUE TITLE
error :Failed to send message. Server closed the connection unexpectedly.

### ISSUE THREAD

**Issue by 101536363** [WongSaang/chatgpt-ui#9]
![image](https://user-images.githubusercontent.com/72073965/222043595-92e703a3-764a-460b-8412-3a143c21119a.png)
![image](https://user-images.githubusercontent.com/72073965/222043655-7954b40a-5348-4563-b366-7e09332b660b.png)
According to your instructions, I added the api-key and successfully accessed the page, but when I asked a question, I was able to reply to the answer and an error message would also appear. Is this normal? I'm building with docker-compose from the latest branch on your git, thanks

**Comment by WongSaang** [comment]
Hello, this is a bug. I have fixed it in the new version. Please pull the latest image again.

**Comment by 101536363** [comment]
ok Thanks

**Comment by 101536363** [comment]
![image](https://user-images.githubusercontent.com/72073965/222054900-6ae13dfc-790f-4a12-9944-15b7221b906b.png)

Hello, I used your docker-compose under Run services on github to start, but when I entered the account admin password password, Request failed, please try again.

**Comment by 101536363** [comment]
Trying to log in to http://localhost:9000/admin will return a page not found

**Comment by WongSaang** [comment]
Thank you very much for your feedback! ❤️

This was an image build error caused by forgetting to remove comments in the Dockerfile. I have updated the image and also the docker-compose configuration example in the Readme file.

You can copy the docker-compose configuration again and pull the latest image by running the command `docker-compose up --pull always`.

手忙脚乱，老兄海涵

**Comment by 101536363** [comment]
ok 3Q  哈哈哈

**Comment by duanyunlun** [comment]
请问这个bug解决了吗？我添加了API-Key依然是返回这个报错

**Comment by WongSaang** [comment]
你能看到容器日志吗？可以的话截个图

**Comment by WongSaang** [comment]
在 wsig-server 添加一个环境变量 `DEBUG=True` ，就会输出错误日志
