### ISSUE TITLE
请问后端有开源的代码吗？

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [WongSaang/chatgpt-ui#92]
rt

**Comment by erritis** [comment]
Yes, https://github.com/WongSaang/chatgpt-ui-server

**Comment by TheLonelinessOfHS** [comment]
> Yes, https://github.com/WongSaang/chatgpt-ui-server

好人一生平安！我还以为是俩不同的项目因为它们在不同的容器里。。。顺便求抓紧修复邮件报错的问题啊！不然都没法开注册

**Comment by WongSaang** [comment]
> 

邮件是什么错？

**Comment by WongSaang** [comment]
目前前端还不支持  mandatory ，可以先使用 optional
