### ISSUE TITLE
怎么才能自己做些微调？

### ISSUE THREAD

**Issue by gooderek** [WongSaang/chatgpt-ui#96]
小白不太懂。docker-compose.yml都是直接拉取作者大佬最新镜像的。如何让docker-compose直接编译本地文件呢

**Comment by WongSaang** [comment]
可以修改代码后docker build, 发布到docker hub 或者其他镜像仓库。
也可以使用 docker-compose.yml 的 build 直接构建后启动服务。
具体可以问 chatgpt ，或者等俺睡醒了给你上代码🤪

**Comment by gooderek** [comment]
我选择等大佬睡醒嘎嘎

**Comment by gooderek** [comment]
大佬牛逼！
